### PR TITLE
feat(Interaction): Added simple script for unify scaling as second gr…

### PR DESCRIPTION
**Pull request by smygarn**
Added a realy simple second grab action script to scale the current object, works just as expected.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 11069acbcdcaea95d6b3137bd4f1882de04824ea
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
There is an option in the existing scale secondary grab script for uniform scaling.

https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Interactions/SecondaryControllerGrabActions/VRTK_AxisScaleGrabAction.cs#L23

**Comment by smygarn** [comment]
I know, but this works more as you expect and is much easier implemented. Please try it out.

**Comment by thestonefox** [comment]
Yes, but if you have improvements or additions to an existing script then do a pr on amending an existing script rather than have 2 scripts that have very similar functionality

**Comment by smygarn** [comment]
Unfortunately I didn't get the original uniform scaling to scale as expected and the original script was too complicated to refactor.

**Comment by thestonefox** [comment]
The uniform scale is only a couple of lines in the existing script. I'd recommend looking at it again and if there are improvements then raise an issue, ask for help in slack and look to improve the existing script.

It's better to have one good working script than 2 scripts where they do the same thing and one works and the other one doesn't work as expected.

**Comment by smygarn** [comment]
I think it ends here as I can still use the script in my application as it extends the base action script.

**Comment by thestonefox** [comment]
@smygarn take a look at this pull request: https://github.com/thestonefox/VRTK/pull/782

It attempts to implement your solution in the existing script for uniform scale.

So rather than using distance, it uses magnitude like your solution and provides a smoother uniform transition.

**Pull request closed without merging**
