### PR TITLE
chore(SDK): provide more meaningful SDK pretty names

### PR DESCRIPTION
**Pull request by thestonefox**
The pretty names for each SDK platform and build target has been
updated to include the library and build target to make it easier
to see which SDK option is for which output device.

### CODE REVIEW

**Comment by thestonefox** [comment]
@bddckr what do you think about these for names?

**Comment by bddckr** [comment]
Oh nice, these offers all the info!

I just noticed that the name "standalone" is a stupid one from Unity, though I don't know whether I like "desktop" more...

**Comment by thestonefox** [comment]
They call it `PC, Mac & Linux Standalone`. Desktop is a hard one because people may be like "yo brah it's a laptop tho"

**Comment by bddckr** [comment]
Yeah go with `Standalone` then. Should be known by Unity using devs.

**Pull request merged**
