### PR TITLE
feat(sdk): implement support for gear vr

### PR DESCRIPTION
**Pull request by gpvigano**
This is the PR #944 by @CoderDawson updated to the latest VRTK version,
modified to be compliant with the new SDK management and with updated
documentation.

Add SDK_GearVRDefines to handle the scripting symbols for the GearVR.

Refactor and update other GearVR/SDK files.

Update documentation (`GearVR_README.md`).

Tested with GearVR:
* object touching and grabbing (005_Controller_BasicObjectGrabbing)
* interaction with Unity UI (034_Controls_InteractingWithUnityUI)
* teleport (044_CameraRig_RestrictedTeleportZones)

The examples were tested after changing `[CameraRig]` and `[VRTK]` in
order to support GearVR.

### CODE REVIEW

**Comment by gpvigano** [comment]
In my fork you can find [a branch with an example project made with Unity 5.5.2](https://github.com/gpvigano/VRTK/tree/gear-vr-test) (sorry, but I haven't the version 5.4 installed).

**Comment by bddckr** [comment]
It looks like GearVR is natively supported by Unity and your SDK classes don't need any other kind of "vendor SDK files", right?

If that is the case you can drop all the `#if`s and the `Defines` file. This is only needed for SDKs that depend on third party assets that one has to download and add to the project first (e.g. SteamVR's plugin).
Look at the Simulator SDK classes for how this is done 😄

**Comment by gpvigano** [comment]
Thank you very much! I did what you suggested and everything still works.
Should I amend last commit or is it safer to add another commit and pull a new request?
Anyway I updated [my test branch](https://github.com/gpvigano/VRTK/tree/gear-vr-test).

**Comment by bddckr** [comment]
Always amend + force push so this PR stays clean and only has one commit. If you ever accidentally do multiple commits you can squash them + force push.

**Comment by gpvigano** [comment]
OK, done. Thanks again for your support.

**Comment by gpvigano** [comment]
Rebased to commit `c7867b1b2beb7958766f737acee7166b4b426ebb` *feat(Interaction): add object touch auto interact script*.
Source code updated according to PR #1040.

**Pull request closed without merging**
