### PR TITLE
feat(sdk): implement support for PSVR with Move Controllers

### PR DESCRIPTION
**Pull request by ababilinski**
This is the skeleton for the PlayStation SDK functionality. The SDK becomes a simulator if the current editor is not PlayStation supported.  You have to download the full PSVR SDK from ps4.siedev.net in order to enable device tracking.

Tested with PlayStation:
* object touching and grabbing (005_Controller_BasicObjectGrabbing)
* interaction with Unity UI (034_Controls_InteractingWithUnityUI)
* teleport (044_CameraRig_RestrictedTeleportZones)
* headset collision fading (011_Camera_HeadSetCollisionFading)
* haptic rumble (016_Controller_HapticRumble)
* custom controller model (032_Controller_CustomControllerModel)
* climbing and falling (037_CameraRig_ClimbingFalling)

The examples were tested after changing `[CameraRig]` to `PSVRCameraRig` and `[VRTK]`  to support PlayStation.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1f22093a94b32f068aa360003f8526c3cf91e1be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 058faed5d648f0f7831b0cd8c2f05c830a79a231
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by yukikaze-ayanami** [comment]
Hello,
I'm going to developing PSVR games.
I want to download this project with "Download ZIP". 
But I'm not familiar with Git.
I'm sorry to trouble you, could you teach me to download PSVR VRTK.

**Comment by thestonefox** [comment]
I'm going to start closing these, we can reopen them if anyone raises it

**Comment by mattboy64** [comment]
@ababilinski it looks like the PSVR classes are partial and I'm not finding the functions when Unity_PS4 is defined. Do you know where I could get those?

**Comment by ababilinski** [comment]
@mattboy64 In order to have the PS4 code you will have to get it from the PlayStation Developer website under VRTK for PSVR

**Comment by manuelmt92** [comment]
Hi, I've been working with the plugin uploaded in Devnet the last few days but it has one year without an update and I am not able to make it work with the last sdk of Unity Asset Store. Is there a chance to have an update or make VRTK work entirely in PSVR? Thanks!!

**Pull request closed without merging**
