### PR TITLE
feat(Simulator): lock mouse by default and hints background

### PR DESCRIPTION
**Pull request by bddckr**
The Simulator allows to lock the mouse when controlling the hands. Since
this is very useful in the Editor it is now enabled by default.
Additionally the Simulator Camera Rig prefab has been updated to make
sure the hints text is always in the top left corner of the screen and
has a background to make reading the text easier.

### CODE REVIEW

**Comment by thestonefox** [comment]
Did you update the camera rig prefab in Unity 5.5 or above?

If so, I've noticed this breaks the prefab in Unity 5.4

Best to do the rebuild in 5.4 so it's forward compatible.

**Comment by bddckr** [comment]
All changes were done in 5.4.4f1. 😩

**Comment by thestonefox** [comment]
Sweet, then i'll take the punt and merge without testing :D

**Comment by bddckr** [comment]
😮 No rush!

**Pull request merged**
