### PR TITLE
feat(HamsterBallLocomotion): Update Camera Rig position by grabbing the interior of a sphere collider - resolves #1630

### LINKED ISSUE #1630: Hamster ball locomotion
The ability to move around by rolling a hamster ball

Like this: https://gfycat.com/OpulentExhaustedGoldenretriever

I'll try and contact the author on reddit: https://www.reddit.com/user/Reil

### PR DESCRIPTION
**Pull request by williamrjackson**
Updates the position of the Camera Rig by rolling a grabbing the sides of a sphere collider's interior, like a hamster ball.

[https://waffle.io/thestonefox/VRTK/cards/5a141a033eb80a02602a376b]

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 388ea0bfe788bdfa5e4d87fcbd3272a928819ec6
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
This pull request needs a tidy up.

Requires a squash and a better commit message so we can clean up the gitcop messages.

Let me know if you need any guidance.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6863447fedda429a5da2f1405140c6555278bcac
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1daf52f2e13abfec29768508f988dfaec3a5fe3c
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a2abe7ca92e76f1a12f194fe3929466b7b52ea0c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by williamrjackson** [comment]
Looks like I'm needing some guidance. I'll take you up on your offer :) Thanks!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c4bf0c973a3e07fd22052c9ba179820ca00a1ad3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by takpare** [comment]
takpar

در تاریخ ۱۶ دسامبر ۲۰۱۷ ۱۱:۲۳ ب.ظ، "GitCop" <notifications@github.com> نوشت:

**Comment by thestonefox** [comment]
I'm going to start closing these, we can reopen them if anyone raises it

**Pull request closed without merging**
