### PR TITLE
	fix(Interaction): handle VRTK_SnapDropZone colliders correctly - fixes #1472

### LINKED ISSUE #1472: Bug: VRTK_SnapDropZone won't accept VRTK_InteractableObject with collider attached to child GameObject
### Environment

 * Source of VRTK Github
 * Version of VRTK: Branch 3.3.0 as of September 01, 2017 (hash c3447b92e789bbb95931c9f3094219ef1d19a4e8 )
 * Version of Unity3D: 2017.1.0f3
 * Hardware used: Vive
 * SDK used: SteamVR

### Steps to reproduce

Using sample scene 41, make the following changes to GameObject Cube_NoHightlightOnTouch (though any example object will do):

1) Remove Mesh Filter, Mesh Renderer and Box Collider from Cube_NoHightlightOnTouch.
2) Add cube primitive as a child of Cube_NoHightlightOnTouch.
3) Drag and drop material from Cube_NoHightlightOnTouch to child Cube (not necessary)
4) Run scene, pick up Cube_NoHightlightOnTouch and attempt to drop in nearby SnapDropZone

### Expected behavior

Cube_NoHightlightOnTouch should snap to SnapDropZone

### Current behavior

Cube_NoHightlightOnTouch will cause the SnapDropZone to highlight, but will not snap. With the collider on a different GameObject than the VRTK_InteractableObject (in this case the child of the VRTK_InteractableObject GO), the OnTriggerEnter/Exit/Stay functions aren't properly testing and tracking the snap status of the parent GameObject with the VRTK_InteractableObject component.

Why does this matter? It's a bit of an edge case, but I think it's valuable for the construction of VRTK_InteractableObject items that have a child object containing the model (mesh filter, mesh renderer and mesh collider), with the remaining scripts attached to the parent object. Best practices and all.

To be even more specific, it would be valuable to cease requiring that the collider be on the parent object alongside the VRTK_InteractableObject component. If a developer needs to tweak the location or scale of the child object (eg. in order to correct the center point or the scale of a crappy Unity Store asset), the collider will need to be attached to the child object along with the visuals so that the renderer and collider bounds match.

### PR DESCRIPTION
**Pull request by bkensey**
The VRTK_SnapDropZone code was assuming that GameObjects with the VRTK_InteractableObject component would also contain a collider.

It would be valuable to allow said GameObjects to have the relevant collider attached to a child object instead of the parent object. The VRTK_SnapDropZone code had no problems with the practice of storing the object mesh filter and renderer on a child object, but it would be valuable to cease requiring that the collider be on the parent object alongside the VRTK_InteractableObject component. If a developer needs to tweak the location or scale of the child object (eg. in order to correct the center point or the scale of a crappy Unity Store asset), the collider will need to be attached to the child object along with the visuals so that the renderer and collider bounds match.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 178518917872766c5bb38c71394a40b8c77d541e
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e44d456549d1deac308d942789d7957882b926c5
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by bkensey** [comment]
Third time's the charm.

**Comment by thestonefox** [comment]
superseded by

https://github.com/thestonefox/VRTK/pull/1479

The issue with this method was it introduces another GetComponentInParent method every frame, which is inefficient as heckidy heck.

The proposed PR removes the GetComponentInParent call and no longer relies on the OnTriggerStay method

**Pull request closed without merging**
