### PR TITLE
feat(Simulator): Simulator enhancements

### PR DESCRIPTION
**Pull request by dantman**
* Add key bindings for WASD so movement bindings can be changed for other keyboard layouts.
* Add context sensitive control hints.
* Add an alternative scene view like mouse movement input mode where a button press is required and the mouse cursor can be locked to the game window.

simulator hmd
simulator controller
simulator lock

### CODE REVIEW

**Comment by thestonefox** [comment]
all of the commit messages need lowercase subject lines

e.g.

`feat(Simulator): allow....` is correct

`feat(Simulator): Allow....` is incorrect

**Comment by dantman** [comment]
Done

**Comment by dantman** [comment]
@virror

**Comment by lxpk** [comment]
The lock cursor doesn't work for me or students when trying to teach VRTK. As written, it only works if you alter sim controller to use the held key for mouse movement, making sim unusable by default. Every attempt to move around or use ALT hand controls clicks out of the scene view.

I think the default should be to have locked cursor whenever simulator runs by default and it should actually work.

**Comment by thestonefox** [comment]
@lxpk you need to raise an issue with steps to reproduce the issue in an example scene so someone can have a look at the issue.

**Pull request merged**
