### PR TITLE
GetControllerElementPath now return empty string #1852

### PR DESCRIPTION
**Pull request by fariazz**
…ad of null #1852

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1c45ea3dde18e92b82ff3847720fe11fba48dfd7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by quintesse** [comment]
@fariazz change your commit locally by doing:

`$ git commit --amend`

Then change the commit message to:

```
fix(Controller): Fix Unity crash

Fix NPE causing Unity to crash by returning `""` from
`GetControllerElementPath()` instead of `null`.
See #1852
```

 And force push the fixed commit using `git push -f`. That should take care of the problems with gitcop

**Comment by bddckr** [comment]
Subject lines need to start lower-case after the colon, so it would be `fix(Controller): fix Unity crash`. We also don't want to mention GitHub issues, that's done by mentioning it in the PR title instead. The commit message body needs to describe the issue and explain what the fix is.

I'd also argue that this should be `work around a crash in Unity 2018.2` instead as that's what it is - it's a Unity bug.

**Comment by quintesse** [comment]
> We also don't want to mention GitHub issues, that's done by mentioning it in the PR title instead.

Aha, it's because I'm used to
http://karma-runner.github.io/2.0/dev/git-commit-msg.html where they specifically mention to put it after the body and I didn't see anything metnioned in the CONTRIBUTING doc. But you guys really don't leave much room for the title, do you? ;)

Anyway, updated the suggestion. All your's @fariazz !

**Comment by bddckr** [comment]
PRs to improve `CONTRIBUTING.md` are welcome, too 😉

**Comment by quintesse** [comment]
@bddckr can't you do the force push for him because he's clearly unresponsive. Or do you want me to open a new PR with a fixed message?

**Comment by bddckr** [comment]
I don't have the time to do it, so a new PR is probably the best. Also note that they accidentally added a newline at the end of the file with this PR which obviously shouldn't be part of the commit either.

**Comment by quintesse** [comment]
@bddckr see https://github.com/thestonefox/VRTK/pull/1873

**Comment by fariazz** [comment]
Sorry my unresponsiveness I was away last week and have been too busy
catching up with work. Ill have a look later today or you can copy the
changes to a new PR, it was really a trivial fix plus testing on my project
(win MR).

**Comment by fariazz** [comment]
Ok I see a new PR has been issued.

Will make sure to format my commits in the right manner next time.

**Comment by bddckr** [comment]
No problem and thanks a lot for finding the time to contribute!!!

**Comment by thestonefox** [comment]
Fixed by https://github.com/thestonefox/VRTK/pull/1873

**Pull request closed without merging**
