### PR TITLE
fix(InteractGrab): Protect against objectToGrabScript.grabAttachMechanicScript being null - fixes #1274  

### LINKED ISSUE #1274: NullReferenceException when programmatically executing IsValidGrabAttempt
### Environment

 * Source of VRTK: Github
 * Version of VRTK: c2fa639d5ce91a2dc340694cb60d1ddaa3f2d2eb
 * Version of Unity3D: 5.6p3
 * Hardware used : Vive
 * SDK used: SteamVR

### Steps to reproduce

* Programmatically execute VRTK_InteractGrab.IsValidGrabAttempt (against an invalid object?)

### Expected behavior

Returns false

### Current behavior

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_InteractGrab.IsValidGrabAttempt (UnityEngine.GameObject objectToGrab) (at Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs:524)
VRTK.VRTK_InteractGrab.PerformGrabAttempt (UnityEngine.GameObject objectToGrab) (at Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs:514)
VRTK.VRTK_InteractGrab.AttemptGrabObject () (at Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs:503)
VRTK.VRTK_InteractGrab.CheckPrecognitionGrab () (at Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs:585)
VRTK.VRTK_InteractGrab.Update () (at Assets/VRTK/Scripts/Interactions/VRTK_InteractGrab.cs:218)
```

### PR DESCRIPTION
**Pull request by trumpetx**
Quick and easy, NRE fix (I have no idea if the reference is supposed to be there still or not - doing this fixes my immediate issue)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98feb44b8be2ec48930fc400f8514e655925f739
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4767f03b0b4ad6e562a7ee20a15c0be3b72740f8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by virror** [comment]
@trumpetx "description" need to start with lowercase

**Comment by trumpetx** [comment]
gitcop didn't yell at me.

**Comment by thestonefox** [comment]
PR that supersedes this one:

https://github.com/thestonefox/VRTK/pull/1276

The linked PR goes a lot further in protecting against null reference exceptions rather than just the one line.

**Comment by thestonefox** [comment]
superseded by https://github.com/thestonefox/VRTK/pull/1276

**Pull request closed without merging**
