### PR TITLE
feat(Interaction): add highlighting options for IOs and SimplePointer

### PR DESCRIPTION
**Pull request by Roballen**
Adding the new VRTK_Destination Highlighter to the SimplePointer will
use the new options in InteractableObject to highlight the object
when the pointer enters.  When the pointer exits, the original material
will be reapplied.

In VRTK_InteractableObject there is a new panel for Targetting Options
and you can set HighLightTarget to true as well as selecting a
HighLightTargetMaterial.  If either of these are false/null, nothing
will happen.

### CODE REVIEW

**Comment by Roballen** [comment]
Not sure if this is something you'd want, but I needed it so here it is.

**Comment by thestonefox** [comment]
Hey, I'll take a look at this soon, I'm just in the process of a hugh pull request that is changing a fair few things. So I'm trying to get it done before looking at pull requests as  i don't want the merge headache :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 112d3ff0b6e199fd202192d4efbe447e904601f4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
You can already highlight objects by just checking the `Interact with Objects` parameter on the `Simple Pointer` script.

This then allows you to interact with objects with the pointer the same as you would with the controller.

**Pull request closed without merging**
