### PR TITLE
feat(SDK): add FixedUpdate routine for controller and headset

### PR DESCRIPTION
**Pull request by thestonefox**
The controller and headset SDK can now execute items within a
FixedUpdate routine if required.

### CODE REVIEW

**Comment by thestonefox** [comment]
@bddckr this is a base PR that adds the FixedUpdate routine.

However doing the angular velocity calculation in FixedUpdate in Oculus 1.11 is too sensitive.

**Comment by bddckr** [comment]
>However doing the angular velocity calculation in FixedUpdate in Oculus 1.11 is too sensitive.

Idea:
1. Move calculation to new method `CalculateAngularVelocity` or something.
2. Use `VRTK_DEFINE_OCULUSVR_UTILITIES_1_11_0_OR_OLDER` and `VRTK_DEFINE_OCULUSVR_UTILITIES_1_12_0_OR_NEWER` from #1022 to conditionally call that new method either in `Update` or `FixedUpdate` respectively.

**Comment by thestonefox** [comment]
@bddckr yeah that could potentially be done in the 1.12 fix PR

I'm still loathed that we can't just use the native stuff :/

Maybe we do this fix now and fix in the future again when we get a response from Oculus about their angular velocity reporting.

**Comment by bddckr** [comment]
Yeah that sounds like a good idea.

**Comment by bddckr** [comment]
I'll rebase the PR on this PR's branch tomorrow I think. Hopefully it feels correct with regard to the velocities...

**Comment by thestonefox** [comment]
shall i merge this then? like it's not gonna cause any issues having it in

**Comment by bddckr** [comment]
Yeah hit the merge button! 😄

**Pull request merged**
