### PR TITLE
feat(Locomotion): translate play area jump into game jump - resolves #393

### LINKED ISSUE #393: Jumping with Headset Movement
I was playing around with the **Climbing/Falling** demo and absolutely loved it. The sensation of dropping off the tower is exhilarating, especially when you have to take a moment to remember the height is not real despite being rather unnatural to '_want_' to drop off from a great height. :smile: 

Coupled with practicing **Jumping** from grabbable surface to grabbable surface, that sensation too feeling great, I was thinking it might be quite cool to have a simple jump mechanic built into the headset that doesn't require actual jumping, nor even a great deal of effort (Threshold parameter). Essentially, if you were to quickly bend your knees and then stand up quickly, you would jump. 

 Mind you in VR you can easily be standing and crouching regularly in some games, so you'd have to test for the magnitude of change along the Y axis in _both directions_. Quick down-to-up movements of the HMD would result in a jump. Quick down movements (dodging incoming fire) without the equally quick upward movement would do nothing. You would have to slightly yet quickly crouch down the quickly stand back up to initiate the jump. 

All these parameters would be tweakable, such as **Jump Window**(if you quickly crouch but then don't quickly stand within the window, you'll be considered crouching and won't jump), **Required Crouch Depth** and both the **Required Magnitude** of the crouch and the subsequent speed of the standing (perhaps these could be tied to a single magnitude, but I was considering that people may do one more quickly than the other).

Thoughts? Could be a fun addition.

### PR DESCRIPTION
**Pull request by ajaxlex**
Adds the player jump script, and demo scene 040 to exercise it.

### CODE REVIEW

**Comment by thestonefox** [comment]
You've been beaten to the finish line, the other PR with example scene 40 is now merged.

You'll have to go to 41 :(

**Comment by ajaxlex** [comment]
Ha! Ok - will pick it up when I get home.

**Comment by ajaxlex** [comment]
Hopefully I will not miss the boat again - modified to 41 in comments and scene number

**Comment by ajaxlex** [comment]
!!  I have some repairs to apply to this ( and which I am putting through their paces in the example scene ) - you should delay pulling until I can get them integrated ( probably wed the 12th )

**Comment by thestonefox** [comment]
Let me know when this is ready to review

**Comment by ajaxlex** [comment]
Jump is fairly reliable, and somewhat simplified ( i think there is plenty to do there ), but there is a nagging issue that remains.  While jumping from column to column in the demo,  I keep teleporting to the ground, I suspect because of code in HeightAdjustTeleport ( Update method ).  I can add code to jump and to heightadj. teleport to listen for jumping, and add that to the growing list of things in IsExternalSystemManipulatingPlaySpace(), but this feels awkward.  I am wondering whether playerPresence has a part to play in negotiating among all these competing behaviors.  I have been trying to think of a nice pattern that would allow for extensibility ( I am contemplating a glide behavior, for example ) without cluttering up the height adj or player presence with a bunch of listeners.

External perspectives are welcome!

**Comment by ajaxlex** [comment]
Maybe an interface IModifiesPlayspace which expects ChangingPlayspace and DoneChangingPlayspace?

**Comment by xEvoGx** [comment]
**HeightAdjust** doesn't prevent you from climbing and then launching yourself into the air (this is how I "jump" from rope to rope in the demo), or simply falling off of high points (you fall, not snap immediately to the ground below), so clearly this is doable within the existing framework?

**Comment by ajaxlex** [comment]
Ok, issue is def. related to HeightAdjust - it goes away when that is not configured.  I will run it down.

**Pull request closed without merging**
