### PR TITLE
chore: Daydream/GoogleVR SDK Integration with VRTK Update

### PR DESCRIPTION
**Pull request by prashant-naidu**
- Modified scripts in  Assets/VRTK/Source/SDK/Daydream/ to be able to handle new prefabs and scripts from latest GoogleVR SDK for Daydream in Unity
- Added new `Daydream` prefab to `SDKSetups` prefab that is used in example scenes

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c6afe448f960274ce0cc118f7e77652e3f4ddc01
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a3231cbe01c290dad0e9a114bc1ea541f193bcd3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 5e67a8f2fa16d4fb6408be9e4f9d3b87e69a8f3a
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ac149cf7335b5cc6b329c3c3c60d6c816df38e2f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 68453992cecdbb7590a9aead1581a8a5a46a950f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 62530f30baed1f1a5048b5bd1af0edb8e89d0ee1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b08da3f3e759f705bc9e0a1e06826f5a7afd2c65
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e03bd83ae0fa60e5739d0111ae797d4c2a0d2db7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 09d40bcaf9ffacc17fdf782b0b0260998d962167
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 4a623ce4d9e7a0a04a4eed3f103e6f67d7dd3a64
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 28de00b98b53616f928bfab4334bb09482f30864
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 59edd05542a72a539528296aa1185d3e5b86c8bc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3355a1d851a0a3a6653caed82cb242f83c40b0d5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fa722a8237455a846b17d7bbd5ec5e3609c6d9a6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cd43170fd0e65e81f1ded0d78aa7c0e9b2034faf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ffd44d6b6f880d7625b1a626d3b27424c6de4693
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: afa885fb62b5281bdc3872e75a2cde228857b6b7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b57ecf08f1b1bc0926c5831ee29c40c513f8a4c7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3369deead1aa402f76aa83681b5d0de5dc81248a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7aa2a5a31b86d739ff7b785c38e64f3261cf5560
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 068edbfd10616aa39bfba0dfc5ec93907f321357
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by prashant-naidu** [comment]
Updated ABOUT and README to match the changes as well

**Comment by prashant-naidu** [comment]
I've tested this update on a couple of the Example Scenes and it works as expected.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c6afe448f960274ce0cc118f7e77652e3f4ddc01
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a3231cbe01c290dad0e9a114bc1ea541f193bcd3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 5e67a8f2fa16d4fb6408be9e4f9d3b87e69a8f3a
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ac149cf7335b5cc6b329c3c3c60d6c816df38e2f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 68453992cecdbb7590a9aead1581a8a5a46a950f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 62530f30baed1f1a5048b5bd1af0edb8e89d0ee1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b08da3f3e759f705bc9e0a1e06826f5a7afd2c65
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e03bd83ae0fa60e5739d0111ae797d4c2a0d2db7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 09d40bcaf9ffacc17fdf782b0b0260998d962167
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 4a623ce4d9e7a0a04a4eed3f103e6f67d7dd3a64
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 28de00b98b53616f928bfab4334bb09482f30864
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 59edd05542a72a539528296aa1185d3e5b86c8bc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3355a1d851a0a3a6653caed82cb242f83c40b0d5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fa722a8237455a846b17d7bbd5ec5e3609c6d9a6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cd43170fd0e65e81f1ded0d78aa7c0e9b2034faf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ffd44d6b6f880d7625b1a626d3b27424c6de4693
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: afa885fb62b5281bdc3872e75a2cde228857b6b7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b57ecf08f1b1bc0926c5831ee29c40c513f8a4c7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3369deead1aa402f76aa83681b5d0de5dc81248a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7aa2a5a31b86d739ff7b785c38e64f3261cf5560
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 068edbfd10616aa39bfba0dfc5ec93907f321357
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 807b402dc62cedf876d336535d28870208f56fa5
  * Your commit message body contains a line that is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
I'm going to start closing these, we can reopen them if anyone raises it

**Pull request closed without merging**
