### PR TITLE
fix(SDK): support SteamVR Plugin version 1.2.0

### PR DESCRIPTION
**Pull request by bddckr**
The SteamVR Plugin has been updated to version 1.2.0 which removed the
method `SteamVR_Util.Event.Listen`. Since it has not been deprecated it
now causes errors to be thrown in VRTK as this method was used within
the SteamVR Controller SDK.

This fix updates the code to use the new API when found, otherwise it
will fall back to the previous API.

### CODE REVIEW

**Comment by bddckr** [comment]
This is an alternative PR for #812 to solve the problem without forcing users of VRTK to do anything.

**Comment by MarkTheLily** [comment]
I added this scripts and now its says
Assets/VRTK/SDK/Base/SDK_InterfaceController.cs(20,92): error CS0426: The nested type `ControllerHand' does not exist in the type `VRTK.VRTK_DeviceFinder'

**Comment by bddckr** [comment]
@MarkTheLily What did you do? Did you apply the changes of this PR to the latest master? It doesn't look like you're using the latest master.

**Comment by MarkTheLily** [comment]
I downloaded latest Master, and overrided  the assets from unity projects folder

**Comment by bddckr** [comment]
@MarkTheLily Given that this PR doesn't touch anything that's mentioned in the error you got I'd say it's nothing in the PR that's doing it.

**Comment by MarkTheLily** [comment]
What is PR?
Unity requested steamvr update hour ago.
I updated it to 1.2.0 
Then I downloaded this master files, placed them on top of the asset files.
Started it up and it won't allow me to access any of my old camera rig setups, because of complied errors.
What else should I have done?

**Comment by thestonefox** [comment]
@MarkTheLily what version of VRTK are you using?

**Comment by MarkTheLily** [comment]
3.0.0

**Comment by thestonefox** [comment]
@MarkTheLily from github or from the Unity Asset Store?

**Comment by MarkTheLily** [comment]
github

**Comment by thestonefox** [comment]
@MarkTheLily Also, what version of unity? And when you say the github version is it the latest master branch you're using?

**Comment by MarkTheLily** [comment]
Just now I downloaded VRTK-fix-steamvr-1-2-0-update version
Unity is the latest 5.5
now I have
Assets/VRTK/SDK/Base/SDK_InterfaceController.cs(20,92): error CS0426: The nested type `ControllerHand' does not exist in the type `VRTK.VRTK_DeviceFinder'

this error

**Comment by thestonefox** [comment]
@MarkTheLily I've tried the PR download in unity 5.4 and 5.5 with the SteamVR 1.1.0 and SteamVR 1.2.0 and I'm getting no errors.

Can you pop into the slack channel and we can try and debug your issue? http://invite.vrtk.io

**Comment by MarkTheLily** [comment]
I have to register right?

**Comment by thestonefox** [comment]
@MarkTheLily yeah but it's free :)

**Comment by bddckr** [comment]
For future searches:
The above error from @MarkTheLily was actually because the old VRTK folder had to be removed completely before upgrading VRTK.

**Pull request merged**
