### PR TITLE
fix(Climbing): change VRTK_PlayerClimb to allow moving objects.

### LINKED ISSUE #697: Climbing does not support moving InteractableObjects
When you grab a moving Interactable Object with the climb interaction it does not move the player alongside the IO. As a player I expect to move alongside the the IO as if I was attached to it.

### PR DESCRIPTION
**Pull request by JoshGalvin**
Allow modeling of Zip Lines, Helicopters, etc...
Fix #697.

### CODE REVIEW

**Comment by mattboy64** [comment]
Did you test the safe zone teleport with this? 

Also could you include an option for rotation?

**Comment by JoshGalvin** [comment]
I haven't tested out the safe zone teleport. I'll do that and add rotation at the same time.

**Comment by lucboudreau** [comment]
Hey guys, I have some code here which I think works better. I've also added support for large rotating objects with precision snap. I've tested the shit out of it and it works awesome. Please consider this code as I find it invaluable to be able to precision snap without needing to add thousands of colliders.

See my comments on the issue.

https://github.com/thestonefox/VRTK/issues/716

**Comment by mattboy64** [comment]
I created a version with movement but also added rotation for the 3.0 version of VRTK here: #903

It would be great to merge all of these climbingMove PRs together and get these finally committed, so please take a look and tell me what you think.

**Comment by AlbertMN** [comment]
Greatly appreciated :)

**Comment by thestonefox** [comment]
Superseded by https://github.com/thestonefox/VRTK/pull/903

**Pull request closed without merging**
