### PR TITLE
feat(SDK): add Ximmerse SDK as a new SDK option

### PR DESCRIPTION
**Pull request by yifu-ximmerse**
This integration is compatible with XimSDKv2.0.1
(https://github.com/Ximmerse/SDK/tree/master/Unity)

Setup up process is very similar to any other SDK:

1. Import XimSDKv2.0.1
2. Add Scripting Define Symbols: VRTK_SDK_XIMMERSEVR
3. Drag VRCameraRig to the scene
4. Use quick switch to set SDK to XimmerseVR
5. Actual Boundaries = VRCameraRig(scene object)
6. Actual Headset = CenterEyeAnchor(scene object)
7. Actual Left Controller = LeftHandAnchor(scene object)
8. Actual Right Controller = RightHandAnchor(scene object)
9. ModelAliasLeftController = _VisibleObject(scene object)
10. ModelAliasRightController = _VisibleObject(scene object)

### CODE REVIEW

**Comment by thestonefox** [comment]
@bddckr does this have all the stuff in now you required for you to do the auto SDK discovery stuff? (i.e. can this be merged and suit your needs?)

**Comment by lacvapps** [comment]
Tested on 5.5.1f1

- Grabbing Objects via "Trigger Click" as "Grab Toggle Button" with VRTK_ControllerEvents it grabs the object and never lets go
- Grip Button click is fired if either side is pressed.  If I press one and then the other a few seconds later it causes the event to fire twice.

**Comment by bddckr** [comment]
@thestonefox Merging is fine now. I see everything I need.

Probably better to first fix those bugs @lacvapps found before we merge, though. :wink:

**Comment by yifu-ximmerse** [comment]
I will work with lacvapps closely to get it fixed.

**Comment by thestonefox** [comment]
@yifu-ximmerse there are a couple of conflicts with this since I merged the Daydream support PR

The SDKManager conflict shouldn't be too hard to resolve, you just need to ensure the Daydream and the Ximmerse SDK are listed.

The `README.md` is also a fairly easy one to resolve, you need to ensure the Daydream stuff is in the supported SDKs and then where you've put the Ximmerse documentation, that now moves to the `GETTING_STARTED.md` file.

**Comment by yifu-ximmerse** [comment]
@thestonefox Hi, StoneFox, I saw my pull request was merge. 
Do I still need to resolve conflicts you mentioned? 
I thought it has to be solved before being able to merged? Please let me know I will get it solved asap.

**Comment by bddckr** [comment]
@yifu-ximmerse You don't need to do anything 😄 @thestonefox did resolve the conflicts when he merged it in.

**Pull request merged**
