### PR TITLE
feat(sdk): implement support for GearVR

### PR DESCRIPTION
**Pull request by gpvigano**
This is the PR #1033 updated to the latest VRTK version,
modified to be compliant with the latest changes to SDK management.

Refactor and update GearVR/SDK files (including latest changes to
`SDK_BaseBoundaries`).

Update documentation (`GearVR_README.md`).

Tested with GearVR:
* object touching and grabbing (005_Controller_BasicObjectGrabbing)
* interaction with Unity UI (034_Controls_InteractingWithUnityUI)
* teleport (044_CameraRig_RestrictedTeleportZones)

The examples were tested after changing `[CameraRig]` and `[VRTK]` in
order to support GearVR.

### CODE REVIEW

**Comment by gpvigano** [comment]
I created a new PR instead of updating the original PR just because I wanted to rename the `gear-vr-support` branch to **`feat/`**`gear-vr-support`, by I haven't found a way to do it, so I created a new branch... Sorry.

**Comment by thestonefox** [comment]
No worries @gpvigano :)

We're trying to get a dev from Oculus to actually help with the testing of this PR :)

**Comment by gpvigano** [comment]
Good to know, thanks for your reply. Anyway, in case you will need my support, I won't be connected to Internet from April 29th to May 17th (I will go on holiday... yes, I'm going to take a break from everything!).

**Comment by thestonefox** [comment]
@gpvigano no worries, have a good break!

**Comment by gpvigano** [comment]
Rebased to a newer commit, fixing errors and updating code, I will "force push" as soon as I finished.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7b7b64d5bd68631656ef5a61734f66562609288b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by gpvigano** [comment]
Sorry, my previous comment is related to my PR #1142, I made a mess with Git, but I hope everything is now OK.

**Comment by timokorkalainen** [comment]
Are the any updates to this? Can we expect GearVR support soon?

**Comment by thestonefox** [comment]
@timokorkalainen I'm currently working on default Unity SDK support (PR here https://github.com/thestonefox/VRTK/pull/1356)

Which will bring natural support for GearVR. Also, GearVR would be supported via the Oculus Utilities SDK support anyway, which is in VRTK now.

**Comment by timokorkalainen** [comment]
@thestonefox Awesome, thank you for the update and hard work!

**Comment by thestonefox** [comment]
Superseded by the default Oculus SDK support for GearVR in the `release/3.3.0-alpha` branch

**Pull request closed without merging**
