### PR TITLE
Fixes root cause of Issue #1379

### PR DESCRIPTION
**Pull request by Eforen**
Fixes root cause of Default Objects Lock up when unsnapped from code #1379

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 71870686e135027477b064c921e9de9ed78633ab
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
You're working on an older version of VRTK. try the latest github master version to see if your issue has already been resolved.

**Comment by Eforen** [comment]
Checking that now

**Comment by Eforen** [comment]
It is still an issue but I didn't notice that I added the lines to the super old version I will refork my repo and make sure it matches my local copy before I change it and resend the pull request

**Comment by thestonefox** [comment]
Duplicate of https://github.com/thestonefox/VRTK/pull/1387

**Pull request closed without merging**
