### PR TITLE
feat(Locomotion): translate play area jump into game jump - resolves #393

### LINKED ISSUE #393: Jumping with Headset Movement
I was playing around with the **Climbing/Falling** demo and absolutely loved it. The sensation of dropping off the tower is exhilarating, especially when you have to take a moment to remember the height is not real despite being rather unnatural to '_want_' to drop off from a great height. :smile: 

Coupled with practicing **Jumping** from grabbable surface to grabbable surface, that sensation too feeling great, I was thinking it might be quite cool to have a simple jump mechanic built into the headset that doesn't require actual jumping, nor even a great deal of effort (Threshold parameter). Essentially, if you were to quickly bend your knees and then stand up quickly, you would jump. 

 Mind you in VR you can easily be standing and crouching regularly in some games, so you'd have to test for the magnitude of change along the Y axis in _both directions_. Quick down-to-up movements of the HMD would result in a jump. Quick down movements (dodging incoming fire) without the equally quick upward movement would do nothing. You would have to slightly yet quickly crouch down the quickly stand back up to initiate the jump. 

All these parameters would be tweakable, such as **Jump Window**(if you quickly crouch but then don't quickly stand within the window, you'll be considered crouching and won't jump), **Required Crouch Depth** and both the **Required Magnitude** of the crouch and the subsequent speed of the standing (perhaps these could be tied to a single magnitude, but I was considering that people may do one more quickly than the other).

Thoughts? Could be a fun addition.

### PR DESCRIPTION
**Pull request by ajaxlex**
Adds the player jump script, and demo scene 041 to exercise it.

### CODE REVIEW

**Comment by xEvoGx** [comment]
Hey alex, here's my snip from Slack:

The only way to go straight up and not forward is to reduce _Forward_ to 0. Easy enough perhaps through a separate script to modify Forward at run-time so you can do either or, but perhaps it's a good idea to include it in your script (such as holding a button on the vive controller to jump up and forward, or even placing the controller in front of you.

Ultimately it would be nice to have locomotion influence jumping up or up/forward/left/right/back. Now that we do in fact have an _arm swinger_ addition to VRTK #664 , that too might not be a bad idea to integrate.

Cheers brother

**Comment by ajaxlex** [comment]
( from slack ) Those are good ideas.  I played Redswood recently, and they use a mechanic where a button is pressed and the controller is swung through the air to cause a jump.  I prefer the visceral association of a real jump motion though.  I had considered incorporating controller orientation into the mix ( amount controllers are moved backward during jump translates into forward motion )

**Comment by xEvoGx** [comment]
Whatever happened to this as it doesn't appear to be a part of the Release?

**Comment by ajaxlex** [comment]
Hey xEvoGx - there was some instability in the jump code that I think is finally fixed.  i have been concentrating on getting my product out the door, then will clean up the more mature code and submit a new pull request.  

The new code does some things like:

- better ground detection 
- dynamic player height detection 
- a public function to force a jump ( use with care! ) 
- a jump inhibitor 
- a lateral offset test that discourages jumps when a player is just picking something up off the ground

Its also considerably more broadly user tested, though it would be good to see it in other application contexts.

**Comment by xEvoGx** [comment]
Awesome, no idea it was even still being worked on!

**Comment by thestonefox** [comment]
I'm going to start closing these, we can reopen them if anyone raises it

**Pull request closed without merging**
