### PR TITLE
add error handling for VRTK_SDKManager

### PR DESCRIPTION
**Pull request by amidofu**
avoid errors caused by null command line args

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 28f5c5bb5b781001d89a16af9f57595dde2cfb4c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by quintesse** [comment]
Not sure why you created this PR. The code you wrote seems redundant.  `VRTK_SharedMethods.GetCommandLineArguements()` can never return `null`.

Also you didn't follow any of the rules in the [CONTRIBUTING](https://github.com/thestonefox/VRTK/blob/master/.github/CONTRIBUTING.md) doc.

**Comment by amidofu** [comment]
Hi, 
I'm sorry that I missed the rules in the contributing doc.
And I found that I got null for the command line args because I use the version on asset store, I didn't notice the difference .
Sorry to bother you.

**Comment by quintesse** [comment]
> Sorry to bother you.

No worries, just trying to help out :)

**Pull request closed without merging**
