### PR TITLE
fix(Locomotion): ensure correct rotation with dash teleport

### PR DESCRIPTION
**Pull request by cameronoltmann**
Fix for incorrect final position during dash teleport with rotation

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 69237d84545fe7574dc696ea5e5e27516de8bcfc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by cameronoltmann** [comment]
Okay GitCop, I've changed my commit title.  Happy now? ;)

**Comment by thestonefox** [comment]
There were a couple of things that needed changing, i've raised a PR with the changes (also to the commit description).

We can either merge my PR (which is basically your PR plus some) or you can update your PR with the changes I made if you want that sweet, sweet PR kudos!

https://github.com/thestonefox/VRTK/pull/1405

**Comment by cameronoltmann** [comment]
Updated to match.

**Comment by thestonefox** [comment]
You'll need to squash it into one commit and ensure the git commit message adheres to the guidelines (e.g. lowercase words in the message).

You could probably just squash and swipe the git message from my commit if you need to.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c2684ea4b8d44af1ad22bdcd2441471763df2f2b
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by cameronoltmann** [comment]
Okay I think I have it sorted out.

**Pull request merged**
