### PR TITLE
feat(SDKObjectAlias): add component copying

### PR DESCRIPTION
**Pull request by bddckr**
The SDK Object Alias script now can copy a list of components over
to the SDK Object in addition to the existing childing.

### CODE REVIEW

**Comment by bddckr** [comment]
I'm kinda torn on this.

I tested by adding a Bloom effect to the game object the SDK Object Alias script is on. That results in a camera being added which we probably _don't_ want to copy over 😛
That's pretty much the reason I scrapped my initial implementation that just copied over every component of the game object (except the Transform and SDKObjectAlias of course).

Another issue are things like ParticleSystem: That one will always throw an error because we set all the fields and properties to be the same after copying the component. But ParticleSystem doesn't like us changing the `randomSeed` after the ParticleSystem is running already.
I guess this can be worked around by turning off the ParticleSystem and turning it on later, after the component is copied over?

Almost feels like one always has to write a helper script (turning off/on ParticleSystems, adjusting a setting, i.e. making sure something is copied over correctly)... One could just do the initial component add and configuration in a script then and no one would need this PR.

Thoughts?

**Comment by thestonefox** [comment]
i wonder if for things that people need to apply directly to the camera in the editor they just have to apply those scripts to every camera rig they're supporting.

**Comment by bddckr** [comment]
Yes that works of course, it means duplicated stuff everywhere, though. And you can't prefab-ify this for the same reasons we need this copying mechanic in the first place.

**Comment by thestonefox** [comment]
I just think the more we try and consolidate the SDK camera rigs, the more hassle we're getting in to. It's like they've been designed to not work together! :p

**Comment by bddckr** [comment]
Something something take over ownership of the VR camera something. Not possible for every SDK I'd guess.

**Comment by thestonefox** [comment]
One day all headsets will be supported through Direct Reality/OpenXR/Unity/Whatever

and we never have to worry about multiple SDK set ups ever again! 😄

**Comment by bddckr** [comment]
You just named 4 different ones. These will be the new things we have to support instead of the current SDKs 😝

**Comment by thestonefox** [comment]
What are your thoughts on this one still? Is it still worth while having the component copy? or is it cludgy?

**Comment by bddckr** [comment]
It works for the original thing we wanted it for: For copying over camera image effect stuff.

**Pull request closed without merging**
