### PR TITLE
feat(Headset): Change head BoxCollider to SphereCollider

### PR DESCRIPTION
**Pull request by virror**
Change head BoxCollider to SphereCollider for a better fit and expose radius and center parameters.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c93d4a329eb3de55177ebf7248e70f5f5cabb656
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by virror** [comment]
Shortened commit message

**Comment by thestonefox** [comment]
Not sure if this is required. The headset is more of a box shape as opposed to a sphere. 

Whilst the head of a person is more akin to a sphere, the head with a headset on is better fit to a box shape.

Plus, if you provide your own collider on the headset object then that is used in place of the box collider anyway. The box collider is just a default if no collider is provided.

**Comment by virror** [comment]
Then feel free to close it : )

**Pull request closed without merging**
