### PR TITLE
Unity 5 5 conditional compilation

### PR DESCRIPTION
**Pull request by Donavan**
This PR removes deprecated functions and replaces them with their new 5.5 versions if we're compiling using 5.5 or later.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 03a6ba1bb10508d310058fdc34fc0ed79afb9b6f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
5.5 won't be supported until it's out of beta as things can still change breaking existing compatibility changes.

**Comment by cameronoltmann** [comment]
The lines that change NavMesh(blah) to UnityEngine.AI.NavMesh(blah) would probably be better handled by adding "using UnityEngine.AI" instead.  One change at the beginning of the file instead of sprinkling changes throughout.

**Comment by thestonefox** [comment]
Superseded by https://github.com/thestonefox/VRTK/pull/777

**Pull request closed without merging**
