### PR TITLE
fix(ControllerReference): check null references

### PR DESCRIPTION
**Pull request by gpvigano**
I tested my PR #1132 (support for gear vr) with your PR #1129 and I found some problems
(I did it by mistake, to be honest, I rebased to the wrong commit...).

Whit your PR I got an exception:
```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_Pointer.PointerEnter (RaycastHit givenHit) (at Assets/VRTK/Scripts/Pointers/VRTK_Pointer.cs:157)
```
The same holds for `PointerExit()`.
Furthermore in `VRTK_BaseGrabAttach.ForceReleaseGrab()` `grabbingObject.GetComponent<VRTK_InteractGrab>()` fails with this exeception:
```
NullReferenceException: Object reference not set to an instance of an object
VRTK.GrabAttachMechanics.VRTK_BaseGrabAttach.ForceReleaseGrab () (at Assets/VRTK/Scripts/Interactions/GrabAttachMechanics/VRTK_BaseGrabAttach.cs:175)

```
An exception occurs also in `VRTK_BaseGrabAttach.ThrowReleasedObject` when `grabbingObjectScript` is null (the Git comparison with the previous version cuold be a bit confusing, there I just added an `if(grabbingObjectScript)` and its square brackets).

After adding some pointer checks in those methods everything works again.

### CODE REVIEW

**Comment by thestonefox** [comment]
Do you have any steps to recreate those errors you were encountering?

**Comment by gpvigano** [comment]
To recreate those errors you can:
* Get the project from [my branch](https://github.com/gpvigano/VRTK/tree/test/gear-vr-controller-reference), see PR #1143
* Import the `Assets/VRTK/SDK/GearVR` folder to your "controller-reference" version
* Open example scene `034_Controls_InteractingWithUnityUI`
* Delete `[CameraRig]` and replace them with empty game object named `[CameraRig]`
* Select the empty `[CameraRig]` and create a new camera, named `Camera` (attached to it)
* Set the **Tag** of `Camera` game object to `MainCamera`
* To move the camera even if you have not a GearVR you can attach to the `Camera` game object the `EditorLikeCameraController` script (Assets/VRTK_GearVR_Test/Scripts)
* Select `[VRTK]` game object
* From **Quick select SDK** select **GearVR**
* Remove **Script Alias Left/Right Controller** references
* Remove `LeftController` and `RightController` from `[VRTK]` game object
* Remove `##Scene Changer##` from `[VRTK]` game object
* Set **Actual Boundaries** to `[CameraRig]`
* Set **Actual Headset** to `Camera`
* Select `Headset` and
  * set **Game Object To Follow** in `VRTK_TransformFollow` script to `Camera` game object
  * check **Activate On Enable** in `VRTK_Pointer`
  * Set **Cursor Visibility** in `VRTK_StraightPointerRenderer` to `Always On`
  * Set **Selection Button** in `VRTK_UI_Pointer` to `Touchpad Press`
  * Add a `VRTK_ControllerEvents` component
* Play
* Use the mouse to move the camera like you do in Editor's Scene View
* Use the mouse left button to interact with UI elements
You will get some of the above exceptions.
To see all the exceptions you can enable the grabbing on the pointer (e.g. changing the scene `005_Controller_BasicObjectGrabbing`)
or you can import also the `VRTK_GearVR_Test` from [my branch](https://github.com/gpvigano/VRTK/tree/test/gear-vr-controller-reference) to your project and test the included scenes in a similar way.

**Comment by thestonefox** [comment]
I've updated the other PR now to take into consideration the things you've found that were causing errors:

https://github.com/thestonefox/VRTK/pull/1129

Try rebasing the PR again you shouldn't get those errors again.

**Comment by gpvigano** [comment]
Maybe it's late, but I confirm: with your PR #1129 no exception is thrown also in my GearVR test project.

**Pull request closed without merging**
