### PR TITLE
perf(object-highlighting): color swap highlighter using MaterialPropertyBlock

### PR DESCRIPTION
**Pull request by fight4dream**
Use MPB to swap color without instancing materials.
Provide an option "resetMainTexture" to 'clear' the _MainTex using Texture2D.white during highlight

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bafd95e13ce44667e99f2dc9882f036b9b7d17c5
  * Your subject line is longer than 72 characters

 * Commit: a80615b20c2acae5752b2ddfab2cb8e0c8c89989
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: d2b55290735ba8d66972b601bb4f08493dc13795
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: e9135c71dca638615339b7cbb831292af03e2e8b
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: dcb722e36f4a0954483100409bf64f6cfb67053d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Not sure which commit is the correct one, I'd recommend squashing the commits into one so it's clear to see what the PR is committing.

**Comment by getwilde** [comment]
Why was this closed? (Was it merged? l was looking forward to this feature.)

**Comment by thestonefox** [comment]
@getwilde I think the commits had gone a bit crazy so they closed it and raised another PR (which also triggered gitcop, so was closed).

I'm guessing they're just trying to get the PR correct.

**Comment by fight4dream** [comment]
yes sorry about the confusion. I (ethan) is quite new to use default GitHub. and i don't know how to squash or even rename the commit.
I have PR another one:
[https://github.com/thestonefox/VRTK/pull/704](url)

**Pull request closed without merging**
