### PR TITLE
Fixes SteamVR compatibility with Unity 2017.1

### PR DESCRIPTION
**Pull request by AndreGroeschel**
Fixes issues with VRTK in Unity 2017.1 where SteamVR camera remains black.

Tested in latest beta 9

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d31502fc905d5ab5159f7506e78ed5cfdc753009
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by bddckr** [comment]
How I crave for the day they finally merge https://github.com/ValveSoftware/steamvr_unity_plugin/pull/14 😩

**Comment by thestonefox** [comment]
Are we better off just doing `Unity_5_6` and not doing a negation of Unity_2017?

**Comment by bddckr** [comment]
I agree with @thestonefox.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d31502fc905d5ab5159f7506e78ed5cfdc753009
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by AndreGroeschel** [comment]
agree! changed it

**Comment by bddckr** [comment]
@AndreGroeschel You'll have to squash your two commits, so only the newest one remains. Make sure the commit message stays good. Also: A small description in form of a commit message body will help to understand the commit in case we later look at it.

May I suggest this?
```
fix(SteamVR): only add SteamVR_UpdatePoses for Unity 5.6

The `SteamVR_UpdatePoses` script was added on Unity 5.6 and newer, but
it's no longer needed to do that in Unity 2017.1.
```

**Pull request closed without merging**
