### PR TITLE
NavMesh areas selectable in editor

### PR DESCRIPTION
**Pull request by sblancodiez**
Custom editor and property for WorldPointer and BasicTeleport so the user can choose NavMesh areas to check for. Used existing variable for distance check.

The previous check with NavMesh.AllAreas allowed pointer and teleport to not walkable points in some circumstances. This way the user can select areas manually.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 32d8093af4f5560c988e981656ccb3ae5e789fe7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 69b8f0c7d933454c4e8c8d24ebec5d4f43ca3358
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
I think this is a good idea, however, lots of the scripts have changed. It would be good to bring this PR up to date with the latest master.

**Comment by thestonefox** [comment]
Superseded with https://github.com/thestonefox/VRTK/pull/1314

**Pull request closed without merging**
