### PR TITLE
fix(HipTracking): move to LateUpdate

### PR DESCRIPTION
**Pull request by virror**
Move from Update to LateUpdate to remove stutter.

### CODE REVIEW

**Comment by thestonefox** [comment]
Why is there stuttering in Update?

May be worth updating the commit message with more of a background as to why this is considered a valid fix?

**Comment by virror** [comment]
This is "just how you should do" tracking, its common knowledge that moving things to follow other moving things in Update usually ends up causing stutter, there are tons of threads about it. When i tried to use this first i immediately noticed quite a lot of stutter and this got rid of all of it.

**Comment by thestonefox** [comment]
Can you link to some of the threads?

**Comment by virror** [comment]
Just try it for your self and you will see that it stutters with the current implementation? : )
Isnt the issue kind of similar to whats described in the Unity docs for LateUpdate: https://docs.unity3d.com/ScriptReference/MonoBehaviour.LateUpdate.html

**Comment by virror** [comment]
Note that this is only tested with the simulator, might not be an issue with the vive, i kind of forgot about that until now : D

**Comment by thestonefox** [comment]
Hah, I mean update the git commit with reasons and links if you have them so people get a better idea when looking through the history :)

**Comment by virror** [comment]
I got that, just wanted your confirmation : D
It sounded a bit like you did not like the pr : p
And now there are stupid conflicts as well, lol

**Comment by virror** [comment]
Updated the commit message, also fixed the conflict but for some reason its still not fixed? No idea whats up with that.

**Comment by bddckr** [comment]
@virror You'll need to squash the commits to only leave the one with the nice commit message.
Maybe @thestonefox can do this since he gets PR access if you have the checkbox on the right side on this page enabled.

**Comment by virror** [comment]
I used the github way of resolving conflicts, thought that was ok since it's only a merge, not a change to the actual product content.

**Comment by bddckr** [comment]
The problem is that that commit shows up as soon it's merged into the master branch.

**Comment by virror** [comment]
Yeah, squash merge should be an option for a pr.

**Pull request closed without merging**
