### PR TITLE
feat(SDK): Implemented support for the Samsung Gear VR

### PR DESCRIPTION
**Pull request by CoderDawson**
Added support for Gear VR via Unity's built-in rendering and input capabilities; no external plug-ins needed. See GearVR_README.md in Assets/VRTK/SDK/GearVR for further details.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b1e28ff8a6c0d6dead1d025a12a074045f0844ba
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b1e28ff8a6c0d6dead1d025a12a074045f0844ba
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by CoderDawson** [comment]
@gpvigano Sorry for the late response; the day job has been pretty busy. Is there an update you need me to make or an easy way I can update the commit message so this can be integrated?

**Comment by gpvigano** [comment]
GitCop rejected your commit because the commit message is too long (>72 characters). See section Commit Messages [CONTRIBUTING.md](https://github.com/thestonefox/VRTK/blob/master/CONTRIBUTING.md).
The problem was not only the commit message, but also the conflicting files.

I'm sorry, I tried to manage this both with rebase and squash, but it just caused me a headache, no success. So I made this PR #1033.

**Comment by gpvigano** [comment]
In [this branch](https://github.com/gpvigano/VRTK/commits/gear-vr-test) you can find a Unity project (made with Unity 5.5.2) with 3 example scenes already modified in order to work with the GearVR (in Assets\VRTK_GearVR_Test).
If you have time to test them, any feedback will be welcome. Thanks again for your work.

P.S. I added my name to GearVR_README.md, but if you think it is better to remove all the names to let everyone change and update this document without adding his/her name, I obviously agree.

**Comment by thestonefox** [comment]
Superseded by the default Oculus SDK support for GearVR in the `release/3.3.0-alpha` branch

**Pull request closed without merging**
