### PR TITLE
refactor(RadialMenu): Change visibility of menuButtons to private

### PR DESCRIPTION
**Pull request by patroclos**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a870d6a26998183fe79becf8275b14eecaf16eb7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f46c4bb135e620f4c08e21c3b5590ee72bbce9ad
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
this shouldn't be private, should be protected so it can be changed in inherited scripts.

**Comment by thestonefox** [comment]
I dont think this should be set to private or protected, if people are trying to add menu buttons at runtime and then disable/reenable the script to generate the new buttons then they'll need access to this parameter.

**Pull request closed without merging**
