### PR TITLE
feat(Keyboard): Add a tracked controller based keyboard input system

### PR DESCRIPTION
**Pull request by dantman**
WIP
===
This is an early work in progress for #899. General comments and ideas are welcome, please [add them to the issue](https://github.com/thestonefox/VRTK/issues/899).

## Current State
Keyboard Layout:
- The keyboard layout scriptable object is implemented
- The editor for keyboard layouts is mostly implemented

`VRTK_Keyboard`:
- Should process key presses (untested)
- Accepts a fixed InputField or one being set by an actor
- Tells the renderer if enter should be enabled
- Editor interface can be used to intuitively create the necessary layout calculator and layout renderer components

Key Layout Renderers:
- Abstract base class with common code
- A Canvas Key Layout renderer with basic functionality for populating a canvas with sized and positioned templates
  - Calculations required to apply RenderableKeyboard Rects to RectTransforms
  - A keyTemplate used to create UI.Button objects from a template
  - keyTemplate UI.Button overrides/modifications:
    - The UI.Button's OnClick
    - The UI.Text's text
    - The UI.Image's sourceImage/sprite
  - A `VRTK_KeyLayoutSprites` scriptable object can be provided to a renderer to give it rule based image/sprite definition for keyset modifier keys
  - specialKeyTemplate handling
- The ability to address a canvas on a different gameobject is implemented, as well as the ability to split the keyboard between multiple canvases
-  Keysets use CanvasGroups and switching between them is partially implemented
- An alternate CanvasLayout based canvas renderer is implemented
  - Doesn't use calculators to calculate the layout (directly uses a source)
  - Creates row containers instead of placing keys directly in areas for maximum flexibility
  - Creates VerticalLayoutGroups in areas, HorizontalLayoutGroups in rows, and LayoutElements in keys
  - Allows you to specify values to use in these group and element scripts
- A "mesh" renderer that renders 3d game objects
  - Basic GameObject rendering
  - A `TextMesh`'s `text` is replaced with the key label
  - A `SpriteRenderer`'s `sprite` is replaced with the sprite

Renderable Key Layouts:
- RenderableKeyboards are almost completely implemented (a meta layout containing Rect locations for areas and keys)
- Split row handling is implemented
- A "Simple" even spaced keyboard layout calculator that can be used to create plain grid-like keyboard layouts with options for spacing in between areas, keys, and rows
- Single area option for grid key layout calculator (can be used to create plain a-z grid keyboards)

Key Layout Sources:
- A `VRTK_KeyboardLayoutSource` extending `VRTK_BaseKeyLayoutSource` implements a simple Key Layout source providing a serialized Keyboard Layout object as the key layout
- 3rd party sources could be created that work by doing something like parsing an XML based keyboard layout and creating a `VRTK_KeyboardLayout` based on it.

## Future work
- KeyboardLayout Editor:
  - Move more button press responses into lambdas with block local variables to reduce possibility of edge case errors
- Canvas Renderer:
  - Special key text overrides
  - `VRTK_KeyLayoutSprites`:
    - Add sprite handling for other special keys (Backspace, Enter, ...)
  - Allow an animation to be provided for the the keyset -> keyset transition (eg: fade using the CanvasGroup's opacity)
  - Disable/make non-interactable the enter key when not usable
    - Add option to swap it with a done key
  - Optional LongPress component to handle subkeys
  - CanvasLayout based canvas renderer:
     - Add a LayoutElement override for some of the keys
- The ability to associate a keyset with an InputField.ContentType
  - On InputField select the content type would pass through KeyboardActor -> Keyboard -> Renderer
  - If there is an ideal keyset that would become active implicitly
  - This could allow InputField.ContentTypes like `IntegerNumber` and `DecimalNumber` to implicitly switch to a number pad keyset on a keyboard.
- Insertion of a spacebar/done row
- `VRTK_MeshKeyLayoutRenderer`
  - Implement collider based keypresses (Anyland and some drum keyboards appear to have something like this)
  - Implement physics based mesh keypresses using small rigid bodies (maybe by using `VRTK_Button`)
  - Add some sort of drumstick like controller elements to the example
- RenderableKeyLayout calculators should output two "interaction regions" for the canvas areas to map the Steam Controller style trackpad cursors
- A physical keyboard style StaggeredKeyboardLayoutCalculator
- A variable key size keyboard layout calculator that can space things similarly to the Steam VR/Controller keyboard
- A keyboard actor responsible for displaying a keyboard on demand in response to text fields
- An additional script optionally responsible for overriding controls when a keyboard is displayed and implementing a Steam VR/Steam Controller style dual touchpad + trigger style interaction for the keyboard canvas.
- Prediction/Autocomplete
  - Prediction display renderers: Responsible for addressing a series of "Prediction Displays" (Canvas UI.Button+UI.Text or 3d gameobject + text), updating text values, and handling presses.
  - `VRTK_BaseKeyboardPredictionEngine`, abstract api responsible for examining an InputField's state and generating predictions for it
  - `VRTK_Keyboard` links to the PredictionEngine to keep it updated on the associated InputField
  - PredictionEngine links to renderer to tell it what words to display and ask for the max number of predictions
  - An optional component to be attached to the InputField may be required to implement certain autocomplete style input behaviours or iOS style word correction highlighting
  - First prediction engine implementation could be based on [Punchkeyboard](https://github.com/rjth/Punchkeyboard)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5d7807bf14f0eac6055579dd8dc8ffc43d917a6b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 4d0486a62a132eedafb5f5a60e8e91869d309147
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5f0022d763783422e6e49dee942be1c1cb320734
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Looks like a lot of work is going into this!

Let me know when you think it's ready for review.

Also, before merging it should probably be squashed into as few commits as possible.

**Comment by dantman** [comment]
Since I ended up having to create 2 class structure implementations for keyboard layouts (`VRTK_KeyboardLayout`=A `row`+`key` based structure you edit, `VRTK_RenderableKeyboardLayout`=An `area`+`key` based structure with `rect` placements for all keys used for displaying) I wanted to at least try to abstract away that implementation fact with interfaces (so code only has to work with an `IKeyset` instead of a `VRTK_KeyboardLayout.Keyset` and a `VRTK_RenderableKeyboardLayout.Keyset`, etc...).

Sadly it seems I've ran headlong into the fact that Unity doesn't support [covariant interfaces](https://msdn.microsoft.com/en-us/library/dd997386(v=vs.110).aspx#Anchor_0) and may have to give up on that or think of something else:
https://github.com/dantman/VRTK/compare/feat/Keyboard...feat/Keyboard-interfaces

**Comment by bddckr** [comment]
> [...] Sadly it seems I've ran headlong into the fact that Unity doesn't support covariant interfaces [...]
Yeah. And it doesn't look like their compiler upgrade will be done anytime soon.

**Comment by dantman** [comment]
I wonder if I could get away with using interfaces in this case by manually casting/cloning each object in `VRTK_KeyboardLayout` and `VRTK_RenderableKeyLayout` to interfaces or something more generic. It would be a little inefficient since I'd essentially have to iterate over and duplicate each list.

But there are only about 3 places I need covariance to cast interfaces:
* The editor that needs to get the names of keysets available in the key layout being used (only executed in the editor)
* The keyboard layout calculator when it passes a `VRTK_KeyboardLayout` to the renderable layout builder (called once when rendering the keyboard)
* The key layout renderer when it asks for a key layout to render from the calculator (called once when rendering the keyboard)

In game, rendering a keyboard only happens once when the keyboard is created; or whenever you force it to render if you're doing something like dynamically replacing the KeyboardLayout with something else (eg: You have an option to switch from QWERTY to Dvorak).

**Comment by thestonefox** [comment]
I'm going to start closing these, we can reopen them if anyone raises it

**Pull request closed without merging**
