### PR TITLE
feat(sdk): implement support for gear vr

### PR DESCRIPTION
**Pull request by gpvigano**
This is the PR #944 by @CoderDawson updated to the latest VRTK version.

Tested on Android/GearVR **only the headset**.

This is here mostly for @CoderDawson, if still interested.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b1e28ff8a6c0d6dead1d025a12a074045f0844ba
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by gpvigano** [comment]
I need GearVR support, so I am already working on this (I looked at [CoderDawson branch](https://github.com/CoderDawson/VRTK/commits/feat/gear-vr) and I haven't found updates).
I will make a pull request as soon as I finish testing and documenting the GearVR support (for now succesfully tested only for UI pointer and teleport). To @CoderDawson: I will make a new commit, excluding your previous commits, otherwise GitCop rejects also newer commits (see above). Anyway I will mention in the commit that is derived from your work.

**Comment by bddckr** [comment]
You can just modify the commit messaging by using interactive rebasing. You probably want to squash all commits into one, though.

**Comment by gpvigano** [comment]
Yes, it's the best choice, I suppose. Thank you for the hint.

**Pull request closed without merging**
