### PR TITLE
feat(SDKManager): runtime SDK switching using SDK Setups

### LINKED ISSUE #817: Create SDK switcher to allow for switching between SDKs at runtime based on headset plugged in
There should be a default way within the toolkit to allow devs to switch SDK at runtime.

### PR DESCRIPTION
**Pull request by bddckr**
> **Breaking Changes**

The SDK Manager is changed by this and therefore users of VRTK will need
to update their SDK Manager configuration to use the new SDK Setups.

Changing the used SDKs at runtime is useful when supporting multiple
devices. Up to now that meant to do some clever hacky stuff with VRTK's
SDK Manager. This change adds a new class `VRTK_SDKSetup` which bundles
specifying the used SDKs and the needed configuration in form of
referenced objects for VRTK.

The SDK Manager now accepts an ordered list of these SDK Setups. This
list can be used automatically at runtime to try initializing and using
the needed VR Devices. If a given Setup can't be used because the VR
Device isn't working or connected, the next entry in the list will be
tried. If no Device is working correctly it will fall back to disable VR
support completely. There are events on both the SDK Manager and Setups
available to be notified about loading or unloading a Setup.

The SDK Manager also allows automatically managing the VR Settings in
the Player Settings based on the SDK Setups list. This only works
correctly if there is only one SDK Manager per project. The introduction
of the SDK Setups should mean there's no need for multiple SDK Manager
anymore, though. If you see the need for multiple SDK Manager after this
change please let @bddckr on the VRTK Slack know about the use case.

Additionally a new prefab and associated script is added to give a GUI
to switch the used SDK Setup at runtime easily.

The SDK Manager editor has been updated to support the SDK Setups and
the button to clear the scripting define symbols now has a friendlier
look that still uses a red background to emphasize its destructive
nature.

The Controller Tracker script has been removed and its logic has been
integrated into the SDK Setup instead. The Tracked Controller now no
longer uses coroutines.

This change also updates the various SDKs to support runtime switching.
Some callback methods have been introduced to `SDK_Base` to allow the
SDKs to react to usage in SDK Setups. The SteamVR Controller SDK has
been updated to use one of those methods to make sure it's possible to
toggle SteamVR off and on at runtime.

The SDKs can now specify multiple different platforms if they support
them. The Ximmerse SDK has been updated to do so.
In addition to that SDKs now specify their used VR Device.

All the example scenes now use the new SDK Manager configuration in
addition to the SDK Setups.

This resolves #817.

### CODE REVIEW

**Comment by bddckr** [comment]
This is still not done as it's still missing some documentation and I still need to update all the example scenes.

**Comment by quintesse** [comment]
With "005_Controller_BasicObjectGrabbing" I'm getting the following error which makes the example unusable:

```
Exception: No default collider prefab could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
VRTK.VRTK_Logger.Log (LogLevels level, System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:160)
VRTK.VRTK_Logger.Error (System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:121)
VRTK.VRTK_InteractTouch.CreateTouchCollider () (at Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs:426)
VRTK.VRTK_InteractTouch.OnEnable () (at Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs:197)
UnityEngine.GameObject:SetActive(Boolean)
SteamVR_ControllerManager:SetTrackedDeviceIndex(Int32, UInt32) (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:160)
SteamVR_ControllerManager:Refresh() (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:228)
SteamVR_ControllerManager:OnDeviceConnected(Int32, Boolean) (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:195)
UnityEngine.Events.UnityEvent`2:Invoke(Int32, Boolean)
Event`2:Send(Int32, Boolean) (at Assets/SteamVR/Scripts/SteamVR_Events.cs:134)
SteamVR:OnNewPoses(TrackedDevicePose_t[]) (at Assets/SteamVR/Scripts/SteamVR.cs:216)
UnityEngine.Events.UnityEvent`1:Invoke(TrackedDevicePose_t[])
Event`1:Send(TrackedDevicePose_t[]) (at Assets/SteamVR/Scripts/SteamVR_Events.cs:127)
SteamVR_UpdatePoses:OnPreCull() (at Assets/SteamVR/Scripts/SteamVR_UpdatePoses.cs:31)
```

**Comment by quintesse** [comment]
Same errors in "006_Controller_UsingADoor" making the doors unusable

Same in "007_CameraRig_HeightAdjustTeleport" but it also has the following error:

```
Exception: No PlayArea could be found. Have you selected a valid Boundaries SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Boundaries SDK from the dropdown.
VRTK.VRTK_Logger.Log (LogLevels level, System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:160)
VRTK.VRTK_Logger.Error (System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:121)
VRTK.VRTK_BodyPhysics.CreateCollider () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:727)
VRTK.VRTK_BodyPhysics.EnableBodyPhysics () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:664)
VRTK.VRTK_BodyPhysics.OnEnable () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:279)
```

BUt the example works fine in the Vive and the Simulator, but switching to "None" spews an endless list of errors:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_BodyPhysics.CalculateVelocity () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:464)
VRTK.VRTK_BodyPhysics.FixedUpdate () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:304)
```

**Comment by quintesse** [comment]
The "009_Controller_BezierPointer" gives me two errors which don't seem to affect the working of the example:

```
Exception: No PlayArea could be found. Have you selected a valid Boundaries SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Boundaries SDK from the dropdown.
VRTK.VRTK_Logger.Log (LogLevels level, System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:160)
VRTK.VRTK_Logger.Error (System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:121)
VRTK.VRTK_BodyPhysics.CreateCollider () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:727)
VRTK.VRTK_BodyPhysics.EnableBodyPhysics () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:664)
VRTK.VRTK_BodyPhysics.OnEnable () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:279)
```

and

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_BodyPhysics.CalculateVelocity () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:464)
VRTK.VRTK_BodyPhysics.FixedUpdate () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:304)
```

And switching to "None" again gives an endless list of errors like for "007":

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_BodyPhysics.CalculateVelocity () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:464)
VRTK.VRTK_BodyPhysics.FixedUpdate () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:304)
```

I think I'll stop for now because I think all these errors are related.

**Comment by bddckr** [comment]
@quintesse Thank you! Looks like you're right and most of these are because of a problem with getting the play area... I'll have a look after I resolved the conflicts.

**Comment by bddckr** [comment]
Should be read to test again now.

**Comment by quintesse** [comment]
So far I have only encountered a very minor thing in "011_Camera_HeadSetCollisionFading" which I think is more something missing in the example than a bug: the simulator won't fade when sticking the head in the wall.

**Comment by quintesse** [comment]
In "013_Controller_UsingAndGrabbingMultipleObjects" if I set the middle whirlygig to rotate and then switch SDKs (for example from SteamVR to Simulator) the whirlygig stops rotating. Not sure if that's considered a bug but I find it surprising.

**Comment by quintesse** [comment]
The "031_CameraRig_HeadsetGazePointer" gives the following error when switching to Simulator:

```
IndexOutOfRangeException: Array index is out of range.
VRTK.VRTK_PlayAreaCursor.GeneratePlayAreaCursor (UnityEngine.Vector3[] cursorDrawVertices) (at Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs:338)
VRTK.VRTK_PlayAreaCursor.InitPlayAreaCursor () (at Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs:241)
VRTK.VRTK_PlayAreaCursor.OnEnable () (at Assets/VRTK/Scripts/Pointers/VRTK_PlayAreaCursor.cs:202)
UnityEngine.Behaviour:set_enabled(Boolean)
VRTK.<ToggleBehaviours>c__AnonStorey3:<>m__0(Behaviour) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:639)
System.Collections.Generic.List`1:ForEach(Action`1)
VRTK.VRTK_SDKManager:ToggleBehaviours(Boolean) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:639)
VRTK.<FinishSDKSetupLoading>c__Iterator0:MoveNext() (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:631)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

In general the example doesn't seem to do anything, but I'm not familiar with it so maybe I'm just missing its purpose. I'll check against vanilla VRTK later.

**Comment by bddckr** [comment]
- Regarding the missing Simulator headset fading in 011: #1090
- Regarding 013: I did only make sure all the scripts get re-toggled when switching the SDKs, it looks like I'll have to make sure the scripts also actually reset properly in their `OnDisable` method for this to work fine. 😄

I'll work on that and your other reports tomorrow. Thanks a ton @quintesse! 👍

**Comment by quintesse** [comment]
The example "035_Controller_OpacityAndHighlighting" gives me 4 errors, 2 for each controller:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_ControllerTooltips.ToggleTips (Boolean state, TooltipButtons element) (at Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs:128)
VRTK.Examples.VRTK_ControllerAppearance_Example.Start () (at Assets/VRTK/Examples/ExampleResources/Scripts/VRTK_ControllerAppearance_Example.cs:55)
```

and

```
Exception: `VRTK_ControllerHighlighter` requires the `Controller Alias GameObject` component. Either the `controllerAlias` parameter is not set or no `Controller Alias GameObject` component is attached to the same GameObject.
VRTK.VRTK_Logger.Log (LogLevels level, System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:157)
VRTK.VRTK_Logger.Error (System.String message) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:118)
VRTK.VRTK_ControllerHighlighter.OnEnable () (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerHighlighter.cs:224)
UnityEngine.Behaviour:set_enabled(Boolean)
VRTK.<ToggleBehaviours>c__AnonStorey3:<>m__0(Behaviour) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:639)
System.Collections.Generic.List`1:ForEach(Action`1)
VRTK.VRTK_SDKManager:ToggleBehaviours(Boolean) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:639)
VRTK.<FinishSDKSetupLoading>c__Iterator0:MoveNext() (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:631)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by quintesse** [comment]
Example "039_CameraRig_AdaptiveQuality" gives me:

```
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[System.Single].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
VRTK.VRTK_AdaptiveQuality.UpdateRenderScale () (at Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs:633)
VRTK.VRTK_AdaptiveQuality.LateUpdate () (at Assets/VRTK/Scripts/Utilities/VRTK_AdaptiveQuality.cs:348)
```

**Comment by quintesse** [comment]
Example "040_Controls_PanelMenu" gives me 3 errors, one for each panel:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.PanelMenuController.Update () (at Assets/VRTK/Scripts/Controls/2D/PanelMenu/PanelMenuController.cs:160)
```

**Comment by quintesse** [comment]
Example "030_Controls_RadialTouchpadMenu" gives me a warning that vanilla VRTK doesn't:

```
The `IndependentRadialMenu` could not automatically find an object to rotate towards.
UnityEngine.Debug:LogWarning(Object)
VRTK.VRTK_Logger:Log(LogLevels, String) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:151)
VRTK.VRTK_Logger:Warn(String) (at Assets/VRTK/Scripts/Internal/VRTK_Logger.cs:113)
VRTK.VRTK_IndependentRadialMenuController:Update() (at Assets/VRTK/Scripts/Controls/2D/RadialMenu/VRTK_IndependentRadialMenuController.cs:188)
```

**Comment by quintesse** [comment]
And "037_CameraRig_ClimbingFalling" gives me an exception that vanilla VRTK doesn't (although the example seems to work fine):

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_PlayerClimb.Ungrab (Boolean carryMomentum, UInt32 controllerIndex, UnityEngine.GameObject target) (at Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs:205)
VRTK.VRTK_PlayerClimb.OnDisable () (at Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs:72)
UnityEngine.Behaviour:set_enabled(Boolean)
VRTK.VRTK_SDKManager:AddBehaviourToToggleOnLoadedSetupChange(Behaviour) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:367)
VRTK.VRTK_PlayerClimb:Awake() (at Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs:59)
```

**Comment by quintesse** [comment]
Ok, that's all I could find :)

**Comment by bddckr** [comment]
- Stopped usage in 013: #1092
- Error in 031: #1091 I don't know either what that scene is showing off. We'll have to figure that one out to properly test if it still works 😅 I saw there's a `Remote_Beam_Controller` scrip on the left alias controller only, so I moved it to the right one and tested but I can't seem to trigger anything. @thestonefox Please tell us how to test this scene, please!
- Errors in 035: Fixed.
- Error in 039: Fixed.
- Error in 040: Fixed. The sliding now works again for me, I just have to make sure to actually swipe, not just drag my thumb slowly from A to B 😄
- Warning in 030: Fixed.
- Error in 037: Fixed.

**Comment by bddckr** [comment]
Thanks to a discussion with @quintesse today:
- I updated all the example scenes to include all the supported SDKs! If an SDK is not installed it will log a warning and try the next one. If no SDK (not even SteamVR) is installed then it will use the Simulator. 🎉
- The SDK Switcher now shows invalid SDK Setups via a _gray_ button, just like the SDK Manager inspector does.

**Comment by quintesse** [comment]
For me 039 still gives the same error

040 works now although I can't get the slider to work at all. Why do you people do to make it work? ^^
I grab the middle object, click on the top part of the pad to pop up the panel and then slide my thumb on the pad from left to right, quickly , slowly, pressing down or not, whatever I try nothing moves. (But it's the same in vanilla VRTK for me)

All the others work now!

**Comment by quintesse** [comment]
Btw, when I add the Oculus SDK the `Setups/OculusVR/VRTK_SDK_Setup` for it is unpopulated and I first have to click the "Populate Now" button.

Otherwise I get two things:

One exception:

```
UnassignedReferenceException: The variable actualHeadset of VRTK_SDKSetup has not been assigned.
You probably need to assign the actualHeadset variable of the VRTK_SDKSetup script in the inspector.
UnityEngine.GameObject.GetComponent[VRTK_TrackedHeadset] () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs:35)
VRTK.VRTK_SDKSetup.SetupHeadset () (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs:489)
VRTK.VRTK_SDKSetup.OnLoaded (VRTK.VRTK_SDKManager sender) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs:381)
VRTK.VRTK_SDKManager+<FinishSDKSetupLoading>c__Iterator0.MoveNext () (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:655)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

and endless warnings:

```
There are 2 audio listeners in the scene. Please ensure there is always exactly one audio listener in the scene.
```

**Comment by quintesse** [comment]
But when I pòpulate the SDK correctly I get endless NREs:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.SDK_OculusVRController.CalculateAngularVelocity (UInt32 index) (at Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs:902)
VRTK.SDK_OculusVRController.ProcessFixedUpdate (UInt32 index, System.Collections.Generic.Dictionary`2 options) (at Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs:64)
VRTK.VRTK_SDK_Bridge.ControllerProcessFixedUpdate (UInt32 index, System.Collections.Generic.Dictionary`2 options) (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:30)
VRTK.VRTK_TrackedController.FixedUpdate () (at Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs:84)
```

**Comment by quintesse** [comment]
The NRE I fixed simply by adding an `if`:

```diff
diff --git a/Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs b/Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
index c27a3b6..dd809a5 100644
--- a/Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
+++ b/Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs
@@ -899,7 +899,10 @@ namespace VRTK
             {
                 var device = GetTrackedObject(GetControllerByIndex(index));
                 previousControllerRotations[index] = currentControllerRotations[index];
-                currentControllerRotations[index] = device.transform.rotation;
+                if (device)
+                {
+                    currentControllerRotations[index] = device.transform.rotation;
+                }

```

**Comment by quintesse** [comment]
@bddckr if you want you could also pick this commit: https://github.com/quintesse/VRTK/commit/1e40f39d7b8ba8a0bafc741be2610e1b7bcc3dde

 - It sets SteamVR as the first in the list of SDKs (after all it's what comes by default with VRTK so why change the default behaviour when you add a new SDK to the project?)
 - It populates all the OculusVR SDKs (although I realised that really should happen automatically, right? but it doesn't seem to do that)

**Comment by bddckr** [comment]
This should be good to test again now.
There could be more scripts that need to be toggled when the current SDK switches. Since the example scenes seem to work fine now I guess those are either non-existent or just not used in the examples 😝

**Comment by quintesse** [comment]
@bddckr I'm still getting the endless list of NREs, but I see now more *why* it is. Because I only get it with example 001 which is the only example that doesn't have Script Aliases set in the SDK Manager! The Oculus  Setup probably doesn't like that. Adding "my if" fixes it leaving only that single NRE I mentioned on Slack:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.SDK_OculusVRController.SetTrackedControllerCaches (Boolean forceRefresh) (at Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs:928)
VRTK.SDK_OculusVRController.GetTrackedObject (UnityEngine.GameObject controller) (at Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs:935)
VRTK.SDK_OculusVRController.GetControllerIndex (UnityEngine.GameObject controller) (at Assets/VRTK/SDK/OculusVR/SDK_OculusVRController.cs:135)
VRTK.VRTK_SDK_Bridge.GetControllerIndex (UnityEngine.GameObject controller) (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:45)
VRTK.VRTK_DeviceFinder.GetControllerIndex (UnityEngine.GameObject controller) (at Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs:49)
VRTK.VRTK_TrackedController.OnEnable () (at Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs:68)
UnityEngine.GameObject:AddComponent()
VRTK.VRTK_SDKSetup:SetupControllers() (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs:528)
VRTK.VRTK_SDKSetup:OnLoaded(VRTK_SDKManager) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKSetup.cs:382)
VRTK.<FinishSDKSetupLoading>c__Iterator0:MoveNext() (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:655)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by quintesse** [comment]
Oh and the "Tracking Origin" for the OVR Manager is still set to "Eye Level" in all the examples.

**Comment by quintesse** [comment]
And I still get the error in 039 (although it doesn't seem to affect anything)

**Comment by quintesse** [comment]
Oh, I just noticed a big problem. For some reason when using SteamVR my  head movement actually rotates the play area not the head!

**Comment by quintesse** [comment]
Btw, when removing the Oculus SDK from the project the SDK_Manager doesn't detect it. It keeps showing the OculusVR as available, Using the "Remove All Symbols" just re-adds the OCULUS  symbols and the "Auto Populate" button still add it (as available). I had to remove the symbols manually for things to work.

**Comment by bddckr** [comment]
TODO:
- SDK Setups prefab (break all prefab links!).
- Use prefab in all example scenes.
- Handle removal of SDK files.

**Comment by quintesse** [comment]
Ready again for testing? :)

**Comment by bddckr** [comment]
I guess so! I'll do the other things on the TODO list above now, but those shouldn't mean any difference to the example scenes.

**Comment by quintesse** [comment]
Everything seems to work great!

Btw @bddckr , how do you make the Oculus SDK show the controllers? (Not the avatar hands) Is that possible?

Also because if I try it with the `LocalAvatar` my Unity crashes ><

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ad1d044c9f49fc787a67b708c389958ffa66ae2c
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by quintesse** [comment]
Nice work @bddckr !

**Comment by bddckr** [comment]
This should be done now and probably needs some final testing.
See #1101 & #1102 for potential errors when testing because these have been extracted into their own PRs.

**Comment by quintesse** [comment]
Example 005 puts me completely outside the floor area (both on Oculus and Steam)

**Comment by bddckr** [comment]
Fixed and added Oculus Avatar to the example scenes. Thanks again to @quintesse 😄

**Comment by quintesse** [comment]
Looks good to me. Let's merge this ****!

**Pull request merged**
