### PR TITLE
feat(haptics): add audio haptics and pulse haptics for Oculus.

### PR DESCRIPTION
**Pull request by virror**
Add the ability to use AudioClips as haptics source for
Oculus and Vive.
Add pulse haptics support for Oculus.

### CODE REVIEW

**Comment by virror** [comment]
Very, very WIP

**Comment by BinaryLegend** [comment]
Any updates on this?

**Comment by thestonefox** [comment]
I think @virror and @cameronoltmann may not have time to look at getting the merge conflicts resolved (as the way haptics are done changed).

I'll try take a look at doing the work to bring this stuff over because it's good stuff.

**Comment by virror** [comment]
Yeah, been a bit busy with other stuff lately, so a bit short on time. Sorry.

**Comment by thestonefox** [comment]
No worries @virror we wont let the good work you've done be in vain! :)

**Comment by virror** [comment]
My life would just be so much better if i was back home with a good computer and a VR setup : p

**Comment by thestonefox** [comment]
@virror one day your dreams will be realised :)

**Comment by virror** [comment]
@thestonefox This should now (once again) be ready for review. Not sure how the CancelCurrentHapticPulse will work with the AudioHaptics though, not sure how that stuff works.

**Pull request closed without merging**
