### PR TITLE
refactor(DestinationPoint prefab): fix typo to read "lockedCursor"

### PR DESCRIPTION
**Pull request by KavanBahrami**
child object was titled "lockedCUrsor", update to "lockedCursor"

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 20ee2c71dc1717692cca2ef30402f13c6d85d10c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by bddckr** [comment]
It looks like you committed a binary file, make sure your project is set to save assets as text files instead. (Edit > Project Settings > Editor IIRC.)

**Comment by thestonefox** [comment]
@KavanBahrami thanks for the PR.

I've raised a PR with a fix (which supersedes this PR). hopefully you can see from the other PR the best practice for future pull requests.

As @bddckr said, you need to switch your asset type to text file and ensure the changes are also minimal.

The final thing to consider is the github subject message and description, they need to adhere to a specific format as outlined in the CONTRIBUTING.md file.

Superseding PR -> https://github.com/thestonefox/VRTK/pull/1285

**Comment by KavanBahrami** [comment]
@bddckr @thestonefox Thanks for the tips! Next pull request will be a bit more on target

**Comment by thestonefox** [comment]
@KavanBahrami no worries :) when you do your next PR it's a good idea to read through the `CONTRIBUTING.md` doc first but then after that we're always around to help out with code reviews to make sure everything is good before it's merged :)

**Pull request closed without merging**
