### PR TITLE
feat(SDK): add native Unity Windows Mixed Reality support

### PR DESCRIPTION
**Pull request by thestonefox**
Support for the Unity Windows Mixed Reality WSA namespace to allow
for Windows Mixed Reality headsets and controllers to be used within
VRTK.

Controller visualisation is provided by a 3rd party repository and
instructions of how to use are provided in the WindowsMR README.md
file.

A massive thanks to @tomwim for all his hard work on this and thanks
to @DDReaper for continued support along the way.

### CODE REVIEW

**Comment by DDReaper** [comment]
Great stuff @thestonefox , will test ASAP

**Comment by thestonefox** [comment]
This still needs a bit of work, the grabbing scene snap handles need adjusting to correctly grab items when using this SDK. I'll try tackle it tomorrow.

(also builds should no longer crash due to another merged PR fixing the issue and that has been rebased into this PR)

**Comment by tomwim** [comment]
Thanks!

For reference: 
PR 1: https://github.com/thestonefox/VRTK/pull/1649
PR 2: https://github.com/thestonefox/VRTK/pull/1743

**Comment by thestonefox** [comment]
@tomwim @DDReaper this PR is now pretty much all working in the build.

I had to attach the velocity estimator script to the camera rig controller GameObjects as velocity wasn't working correctly, it seems fine now.

The one last problem is I don't seem to be able to do a Windows Platform build when using the controller visualisation, every time i try and build I get an error about the gLTF stuff missing.

**Comment by tomwim** [comment]
That's what I meant with the UWP folder? I haven't found a solution yet...

**Comment by thestonefox** [comment]
@tomwim I tried putting the UWP at the root of the project but didn't seem to help

**Comment by tomwim** [comment]
What are the errors?

**Comment by thestonefox** [comment]
@tomwim horrible error dumps incoming ;)

Error One:
```
Failed running D:\Unity\Editor\Data\il2cpp/build/UnityLinker.exe --api=NET_4_6 -out="D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\tempStrip" -l=none -c=link --link-symbols -x="D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Core.xml" -f="D:\Unity\Editor\Data\il2cpp\LinkerDescriptors" -x "D:\Users\xx\VRTK/Temp\StagingArea\Data/methods_pointedto_by_uievents.xml" -x "D:\Users\xx\VRTK/Temp\StagingArea\Data/UnityEngine.xml" -x "D:\Users\xx\VRTK\Temp\StagingArea\Data\preserved_derived_types.xml" -x "D:\Unity\Editor\Data\il2cpp\LinkerDescriptors\mscorlib45.xml" -x "D:\Unity\Editor\Data\il2cpp\LinkerDescriptors\System45.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Accessibility.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\AI.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Animation.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\AR.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\AssetBundle.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Audio.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Cloth.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Core.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\CrashReporting.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Director.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\GameCenter.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Grid.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\ImageConversion.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\IMGUI.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Input.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\JSONSerialize.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\ParticlesLegacy.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\ParticleSystem.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\PerformanceReporting.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Physics.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Physics2D.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\ScreenCapture.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\SharedInternals.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\SpriteMask.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\SpriteShape.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\StyleSheets.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Terrain.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\TerrainPhysics.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\TextRendering.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Tilemap.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UI.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UIElements.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UNET.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityAnalytics.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityConnect.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityWebRequest.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityWebRequestAudio.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityWebRequestTexture.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\UnityWebRequestWWW.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Vehicles.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Video.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\VR.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Web.xml" -x "D:\Unity\Editor\Data\PlaybackEngines\MetroSupport\Whitelists\Wind.xml" -d "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\Assembly-CSharp.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\UnityEngine.UI.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.CJK.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.MidEast.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.Other.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.Rare.dll" -a  "D:\Users\xx\VRTK\Temp\StagingArea\Data\Managed\I18N.West.dll"

stdout:
Fatal error in Unity CIL Linker
Mono.Linker.MarkException: Error processing method: 'GLTF.Schema.Scene GLTF.Schema.GLTFRoot::GetDefaultScene()' in assembly: 'GLTFSerializationUWP.dll' ---> System.ArgumentNullException: Value cannot be null.
Parameter name: instruction
   at Mono.Cecil.Cil.InstructionOffset..ctor(Instruction instruction)
   at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
   at Mono.Cecil.Cil.CodeReader.ReadScopes(Collection`1 scopes)
   at Mono.Cecil.Cil.CodeReader.ReadScope(ScopeDebugInformation scope)
   at Mono.Cecil.Cil.CodeReader.ReadDebugInfo()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.MethodDefinition.<>c.<get_Body>b__41_0(MethodDefinition method, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at UnityLinker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at UnityLinker.Steps.UnityMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at UnityLinker.UnityDriver.Run()
   at UnityLinker.UnityDriver.RunDriver()
stderr:

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:128)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:89)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:82)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:204)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:114)
UnityEditorInternal.IL2CPPBuilder:Run() (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:152)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
PostProcessUAPIl2Cpp:RunIL2CPP() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUAPIl2Cpp.cs:378)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:231)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Error Two:
```
Exception: D:\Unity\Editor\Data\il2cpp/build/UnityLinker.exe did not run properly!
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:130)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:73)
UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (IEnumerable`1 args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:89)
UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String[] assemblies, System.String[] searchDirs, System.String outputFolder, System.String workingDirectory, System.String& output, System.String& error, System.String linkerPath, IIl2CppPlatformProvider platformProvider, IEnumerable`1 additionalBlacklist) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:82)
UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (System.String stagingAreaData, IEnumerable assemblies, System.String managedAssemblyFolderPath, System.String[] assembliesToStrip, System.String[] searchDirs, System.String monoLinkerPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:204)
UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:114)
UnityEditorInternal.IL2CPPBuilder.Run () (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:152)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry, Boolean debugBuild) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:34)
PostProcessUAPIl2Cpp.RunIL2CPP () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessUAPIl2Cpp.cs:378)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:231)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:117)
UnityEditor.WSA.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:124)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Error Three
```
Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Error Four
```
UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0020e] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:181 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00065] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:88 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by tomwim** [comment]
Oooh, never seen those errors. I think that's unrelated to the UWP folder issue...sorry

**Comment by thestonefox** [comment]
can you see if it builds for you?

**Comment by tomwim** [comment]
Found another issue:

If you're on Standalone and do not have SteamVR installed it complains about missing references. Is there an additional check needed? 

This is one of the problems, the rest is similar.

`Assets/VRTK/Source/SDK/SteamVR/SDK_SteamVRController.cs(8,11): error CS0246: The type or namespace name "Valve" could not be found. Are you missing an assembly reference?`

**Comment by tomwim** [comment]
@thestonefox Builds fine for me. Got the newest VRTK PR and added the Extension (cloned into assets, not downloaded as zip). No build issues after moving the UWP folder to root

**Comment by tomwim** [comment]
Which Unity version are you using?

**Comment by thestonefox** [comment]
@tomwim you shouldn't be getting issues if SteamVR is not installed, double check your script define symbols, clear them out and let VRTK set them again.

I'm guessing you have the VRTK SteamVR script define symbol still around

**Comment by thestonefox** [comment]
@tomwim I'm on Unity 2017.3

I'm wondering if its more to do with me missing some requirements within Unity rather than actually the WMR support in VRTK. Feels like I don't have the correct .net or something like that

**Comment by DDReaper** [comment]
OK, one issue on initially loading up this PR, is that Standalone has loads of failures if SteamVR isn't installed yet.  Not had this before, so I suspect there is a define in the project that shouldn't be there yet by default?
@thestonefox ?

**Comment by DDReaper** [comment]
OK, when running in the editor, everything seems fine.  However, when I build for a UWP project, I get a ton of errors, some nothing to do with WinMR
image

Note, this is without the visualiser added to the project.

**Comment by thestonefox** [comment]
@DDReaper I done goof https://github.com/thestonefox/VRTK/blame/release/3.3.0-alpha/ProjectSettings/ProjectSettings.asset#L595-L610

I'll raise a PR to remove the define symbols.

In regard to your other errors, can you do me a favour and check your Project Settings and check the Virtual Reality platforms in the XR setting.

I bet yours is set to
```
None
OpenVR
```

I think it should be
```
Windows Platform
```
(or whatever it is)

If it is, then something is wrong there

**Comment by DDReaper** [comment]
On Standalone, it's set to None/OpenVR, for UWP it's set to WindowsMR.
I'm guessing some new reflection code got added which isn't supported or is different on UWP. (usual culprit)

**Comment by thestonefox** [comment]
@ddreaper I remember in the pr from @tomwim he had some define symbols to ignore some code. I wonder if they're needed

**Comment by DDReaper** [comment]
Yes, you need to use #if !UNITY_WSA to block off code from UWP if it's not needed.
If I get time, I'll look through. But don't remember having this issue last time I tested, so it must be new.

Only issue is, if this new code is also needed on UWP, then you'll need alternative code for UWP using UWP libraries.

**Comment by DDReaper** [comment]
OK, working on a PR to that branch to resolve those UWP platform issues. Got most of them fixed, just testing now

**Comment by DDReaper** [comment]
Pushed a PR #1749 to update the WinMR branch with UWP fixes

**Comment by thestonefox** [comment]
@DDReaper is your project setting scripting backend `.NET` or `IL2CPP` ?

**Comment by tomwim** [comment]
So if I remember correctly most of the defines I put into the original code was to make .NET work. 
To be honest, .NET is worse than IL2CPP and IL2CPP is already a shit show. The whole UWP thing is just super annoying and I feel like it causes more problems than it solves

**Comment by thestonefox** [comment]
@tomwim yeah I can get a IL2CPP build to work without any defines, so it's probably the .NET thing that needs them

**Comment by DDReaper** [comment]
Yes, you're correct. It only affects .Net builds.  I never use IL2CPP on anything other than iOS and Android. On windows, it's just spanners

**Comment by thestonefox** [comment]
@DDReaper you know when you do a .net build, where is the executable stored in the final build files?

**Comment by thestonefox** [comment]
@DDReaper nevermind, I realise it just builds you a visual studio project that you then have to build again.

I can get that far, but when you run the final built project you get errors, I'm assuming because the build settings scene array is empty and therefore it cannot inject the constructor scene.

**Comment by DDReaper** [comment]
Ok, @bddckr / @thestonefox
I've posted an alternate proposal for the UWP Build issues.
https://github.com/ddreaper/VRTK/tree/feat/windows-mixed-reality-support-UWPUpdate2
This one uses extension methods to resolve the majority of the UWP Build issues, with the remaining items that couldn't be resolved with extensions done to the bare minimum.

Let me know which PR you want to merge.

**Comment by DDReaper** [comment]
> I can get that far, but when you run the final built project you get errors, I'm assuming because the build settings scene array is empty and therefore it cannot inject the constructor scene.

When I ran it here (after checking all the build scenes were in) it actually ran fine.

**Comment by SimonDarksideJ** [comment]
Works fine here building for x86 /x64 with UWP / Mixed Reality enabled.  Ship it 🗡 
image

**Comment by thestonefox** [comment]
@SimonDarksideJ Can you post the steps you're doing to create a successful build.

I still can't get it to work, but I may be doing something wrong.

**Comment by SimonDarksideJ** [comment]
OK, steps I used to "run" the build:

1. Clone
2. Open in Unity
3. Set platform to UWP
4. I did have to change the scripting backend in the UWP player to .NET, but only because I don't have IL2CPP installed
5. In player settings, enable XR and set it to Windows Mixed Reality
6. Opened the SDK scene, just to set the platform defines automatically (not sure if that's needed)
7. Opened build settings and confirmed the Scenes were all there in order
8. Built to a new folder for UWP
9. Opened new UWP VS project
10. set the target platform to x86 (ARM won't work)
11. Built it.
12. Started the MR portal (checked it was in the cliff house)
13. Ran the project

All went' smoothly with all the ducks in a row (as it were), could even switch scenes (once I learned how to)

**Comment by thestonefox** [comment]
@SimonDarksideJ I've managed to successfully build (thanks to your instructions!)

I would like someone else to independently verify it's working for them too, but if no one steps up to the plate then I'm happy to just merge this!

**Comment by SimonDarksideJ** [comment]
@tomwim do you have scope to test so we can get this merged?

**Comment by jethrogillgren** [comment]
Hi all,
I'm unsure if this is expected, but the branch does not work on the Hololens.
The Hololens WMR device doesn't use controllers, but I was hoping that despite this VRTK would run on the platform.  I use a Unity asset which relies on VRTK for movement stuff, and wanted to get it running on hololens.

Would it be helpful to post the errors I'm getting, or is support for Hololens not intended?

**Comment by tomwim** [comment]
@thestonefox @SimonDarksideJ I am running this since the beginning and it works fine with me. No build issues (also appxbundle builds are working). I bet there are still some flaws in it but will try and do as many PRs as possible to fix them over time. Working with it on a daily basis so I'm sure there will some stuff come up 

@jethrogillgren No, this is just for the Immersive Headset. Hopefully some day HoloLens support will be implmented. But I actually run it with HoloLens though. No functionality but all of VRTK is in and I don't get any errors.

**Comment by jorgeolothar** [comment]
I followed the steps for WMR headset.

#6 is necessary, at least in a new project. Tried it without it and got the errors mentioned previously in the thread.

#13 Refers to running the project from VS, right? I tried double clicking the only executable I could find, "\Virtual Reality Toolkit\bin\x86\Debug\Virtual Reality Toolkit.exe"and it didn't work. Pressing "> Local Machine" in VS did it

- Some warnings about "The referenced script on this Behaviour (Game Object 'OVRCameraRig') is missing!" and the like. I assume because I didn't add corresponding SDKs to the project so probably fine.

-No 3D model rendering for controllers... makes some of the example scenes difficult. I see there are some custom hands in the scene, didn't get to see those either.

Otherwise seems fine.

**Comment by tomwim** [comment]
Did you include the Extension for visualization? I have to say I sometimes have issues with the controller models in Editor too but most of the time when the tracking is off and just replaying the scene helps. No issues in builds ever.

**Comment by SimonDarksideJ** [comment]
So responding to each @jorgeolothar 

* Step 13: If you have an EXE, then you haven't switched to the Universal Windows Platform in step 3, as UWP doesn't use EXE's :D they are an appx project.

* Warnings - these are normal and is how VRTK works, the SDK scene has configuration for all SDK types, if you don't have those SDK's installed, you will see these warnings.  They can safely be ignores

* Controllers - As @tomwim if you want the MR Controllers showing up, then you need to use the visualizer and the visualiser define

**Comment by jorgeolothar** [comment]
@SimonDarksideJ 

> you haven't switched to the Universal Windows Platform
I have. Instruction number 13 is confusing/ambiguous for someone who has never built or run a project in VS, which I assume is most of the VRTK users. "Run the project" just had me looking for a resulting executable file from the build process of the previous step (which I found one, but not a windows executable apparently). It only became apparent to run it from VS afterwards.

>then you need to use the visualizer and the visualiser define
These are new to me. Do you mean https://github.com/Innoactive/VRTK-Windows-MR-Extension? I keep getting errors: 'The type or namespace name `GLTF' could not be found'

**Comment by thestonefox** [comment]
@jorgeolothar the GTLF error you're getting is due to how you downloaded the extension repo. If you just download it then it will mark all the DLLs as unsafe and therefore they won't register with Unity.

You'll probably have to go through each dll and mark it as safe for it to work. I think the plan in the future is that repo will be it's own Unity asset where that won't be a problem.

**Comment by SimonDarksideJ** [comment]
@thestonefox is correct, you need to either clone the Visualiser repo or use an asset created from the project (which I believe @tomwim is sorting as he created the repo).
sadly, GitHub's "download zip" feature doesn't work for compiled DLL's.

I've updated the instructions to be a bit clearer @jorgeolothar . Note these only work on a Windows Machine, as you need Window to compile to Windows UWP. Just like you need a Mac to compile to iOS.

**Comment by thestonefox** [comment]
@SimonDarksideJ I fixed the issue where the Windows Mixed Reality SDK wasn't being added to the project settings automatically.

I think we should merge this, then I may look into the issue where you have to open the constructor scene to set up the scripting defines.

**Comment by SimonDarksideJ** [comment]
Woot 🗡

**Pull request merged**
