### PR TITLE
Feat/vrtk multiple outline object copy highlighter

### PR DESCRIPTION
**Pull request by Thumann**
Support for multiple highlighters as described in [#879](https://github.com/thestonefox/VRTK/issues/879)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00271437b183b381a4bc41211d661b41ea35f852
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
The commits need squashing into 1 commit (do an interactive git rebase and squash them then force push back up)

**Comment by thestonefox** [comment]
How much of this code is shared with the standard outline highlighter?

Could the outline highlighter work as the base for this script and remove any repetition of code?

**Comment by thestonefox** [comment]
I think looking at it, it may be better to extend the existing outline object copy to just use an array for customOutlineModel and customOutlineModelPath, rather than have 2 scripts that do mostly the same thing.

**Comment by thestonefox** [comment]
Potential PR to supersede this PR

https://github.com/thestonefox/VRTK/pull/935

It just updates the existing outline highlighter to accept multiple objects

**Comment by thestonefox** [comment]
Superseded by https://github.com/thestonefox/VRTK/pull/935

**Pull request closed without merging**
